(()=>{
const A={
 ectopicS:{emoji:'🚨',en:'Surgical Ectopic Emergency',ar:'طوارئ الحمل الهاجر الجراحية',patient:'Maya',details:'28 y • 7 weeks • unstable',refs:['NICE NG126','ACOG ectopic pregnancy guidance'],qs:[
['Arrival','A 28-year-old at 7 weeks has severe unilateral pain, syncope and vaginal bleeding. BP 78/46, HR 136.','ما أول خطوة؟',['Assess ABCs, resuscitate and call the emergency team','Wait for serial β-hCG','Give methotrexate immediately','Discharge with follow-up'],0,'Instability makes immediate stabilization and escalation the priority.','عدم الاستقرار يجعل التثبيت الفوري وتصعيد التدبير أولوية.'],
['Access','She remains pale and hypotensive.','ما الإجراء الداعم المناسب؟',['Establish large-bore IV access and send urgent blood tests/crossmatch','Delay IV access until ultrasound','Give oral fluids only','Wait for a repeat pregnancy test'],0,'Rapid vascular access and blood preparation support resuscitation.','الوصول الوريدي السريع وتحضير الدم يدعمان الإنعاش.'],
['Diagnosis','Ultrasound shows no intrauterine pregnancy and significant free fluid.','ما التشخيص الأرجح؟',['Ruptured ectopic pregnancy','Normal early pregnancy','Placenta previa','Hyperemesis gravidarum'],0,'The clinical picture plus free intraperitoneal fluid strongly supports rupture.','الصورة السريرية مع السائل الحر تدعم بقوة الحمل الهاجر المتمزق.'],
['Priority','The patient is still unstable despite initial resuscitation.','ما الخطوة التالية؟',['Prepare for urgent operative management while resuscitation continues','Wait for serial β-hCG results','Start outpatient methotrexate','Observe for 24 hours'],0,'Definitive treatment should not be delayed in an unstable suspected rupture.','لا ينبغي تأخير التدبير النهائي في حالة الاشتباه بالتمزق مع عدم الاستقرار.'],
['Team','The OR team is mobilizing.','من المهم إشراكه مبكرًا؟',['Anaesthesia, surgery and blood bank/critical care as available','Only the receptionist','No one until imaging is repeated','Only the laboratory'],0,'This is a multidisciplinary emergency requiring coordinated resuscitation and surgery.','هذه حالة إسعافية متعددة الاختصاصات تتطلب تنسيق الإنعاش والجراحة.'],
['In theatre','At surgery, hemoperitoneum is confirmed.','ما المبدأ الجراحي؟',['Control the source of bleeding and complete definitive management appropriate to the patient','Close the abdomen without controlling bleeding','Delay haemostasis for more imaging','Give methotrexate instead of surgery'],0,'The operative priority is haemorrhage control and definitive treatment.','الأولوية الجراحية هي السيطرة على النزف والتدبير النهائي المناسب.'],
['Reassessment','After haemostasis, BP improves but remains borderline.','ما الأولوية؟',['Continue haemodynamic monitoring, reassess bleeding and guide blood products by the clinical picture','Stop monitoring','Send to the waiting room','Ignore urine output'],0,'Postoperative reassessment is essential after major haemorrhage.','إعادة التقييم بعد النزف الكبير ضرورية.'],
['Safety','The patient asks why surgery was needed.','ما أفضل explanation؟',['The suspected rupture and instability made urgent surgical treatment safer than waiting','Surgery was chosen because ultrasound is always unnecessary','Methotrexate never works','All ectopic pregnancies require hysterectomy'],0,'Explain the clinical reasoning and uncertainty honestly.','اشرح منطق القرار السريري والشكوك بوضوح.'],
['Complication','She develops increasing tachycardia postoperatively.','ما التصرف؟',['Reassess ABCs, bleeding and haemodynamics and escalate if deterioration is confirmed','Assume anxiety only','Discharge immediately','Ignore the change'],0,'New deterioration after haemorrhage requires structured reassessment.','أي تدهور جديد بعد النزف يستلزم إعادة تقييم منهجية.'],
['Debrief','Which principle best summarizes the case?','ما المبدأ الأهم؟',['In an unstable suspected ruptured ectopic, resuscitation and definitive surgical management proceed urgently together','Always wait for β-hCG','Always use methotrexate first','Never involve anaesthesia'],0,'The key is rapid recognition, resuscitation and definitive management without dangerous delay.','المبدأ هو التعرف السريع والإنعاش والتدبير النهائي دون تأخير خطير.'] ]},
 pphS:{emoji:'🩸',en:'Massive PPH — Surgical Escalation',ar:'نزف ما بعد الولادة — التصعيد الجراحي',patient:'Nour',details:'31 y • 15 min postpartum',refs:['WHO Consolidated PPH Guideline 2025','WHO PPH Implementation Guide 2026'],qs:[
['Alarm','Heavy bleeding starts after vaginal birth; HR 128, BP 88/54.','ما أول خطوة؟',['Call for help, ABC assessment, quantify blood loss and start resuscitation','Wait for a scan before acting','Give analgesia only','Discharge'],0,'PPH is time-critical and requires immediate coordinated response.','نزف ما بعد الولادة حساس للوقت ويحتاج استجابة منسقة فورية.'],
['Cause','The uterus is boggy.','ما السبب الأرجح؟',['Uterine atony','Ectopic pregnancy','Pulmonary embolism','Hyperemesis'],0,'A boggy uterus strongly suggests atony.','الرحم الرخو يشير بقوة إلى وهن الرحم.'],
['First response','Atony is suspected and bleeding continues.','ما التدبير المناسب؟',['Uterine massage and uterotonic treatment according to local protocol while resuscitation continues','Wait for CT','Stop monitoring','Give methotrexate'],0,'Immediate first-line measures should not be delayed.','لا ينبغي تأخير التدابير الأولية الفورية.'],
['TXA','PPH is clinically diagnosed.','ما الإضافة المبكرة المهمة؟',['IV tranexamic acid as soon as possible and within 3 hours of birth, according to protocol','Delay TXA until surgery','Give oral iron only','Wait until tomorrow'],0,'WHO recommends early IV TXA in clinically diagnosed PPH, within 3 hours of birth.','توصي WHO بالترانيكساميك الوريدي مبكرًا عند تشخيص PPH وخلال 3 ساعات من الولادة.'],
['Escalation','Bleeding reaches 2,000 mL and continues.','ما الخطوة؟',['Activate major haemorrhage response and prepare definitive bleeding control','Continue observation alone','Stop IV access','Wait for spontaneous resolution'],0,'Persistent severe bleeding requires rapid escalation and blood support.','النزف الشديد المستمر يحتاج تصعيدًا سريعًا ودعمًا بالدم.'],
['OR','Medical measures fail and atony persists.','ما المبدأ؟',['Move promptly to definitive mechanical or surgical control according to expertise and cause','Keep repeating ineffective measures indefinitely','Discharge','Wait six hours'],0,'Failure of initial measures should trigger timely definitive control.','فشل التدابير الأولية يستدعي السيطرة النهائية في الوقت المناسب.'],
['Surgical choice','A uterus-sparing procedure is feasible and appropriate for the situation.','كيف تفكر؟',['Choose an effective haemorrhage-control option suited to the cause, fertility goals and local expertise','Choose hysterectomy automatically in every PPH','Avoid all procedures','Treat only the haemoglobin'],0,'Surgical choice depends on cause, severity, fertility considerations and expertise.','الاختيار الجراحي يعتمد على السبب والشدة والرغبة بالخصوبة والخبرة.'],
['Reassessment','Bleeding decreases after intervention.','ما التالي؟',['Continue close monitoring, quantify ongoing loss and reassess haemodynamics and labs','Stop all monitoring','Send home immediately','Remove all IV access'],0,'Improvement requires continued surveillance because rebleeding can occur.','التحسن يحتاج مراقبة مستمرة لأن عودة النزف ممكنة.'],
['Coagulopathy','Bleeding is ongoing and laboratory results suggest worsening coagulation.','ما المبدأ؟',['Treat haemorrhage while correcting coagulopathy with blood components guided by clinical/laboratory assessment','Ignore coagulation','Give oral fluids only','Delay all treatment'],0,'Severe haemorrhage can cause coagulopathy requiring coordinated blood-component therapy.','النزف الشديد قد يسبب اعتلال تخثر يحتاج تدبيرًا منسقًا بمكونات الدم.'],
['Debrief','What is the key learning point?','ما أهم درس؟',['Early recognition, resuscitation, cause-directed treatment and timely escalation save time and lives','Surgery should always be first','Blood loss should be estimated by eye only','TXA replaces all other treatment'],0,'PPH management is a coordinated sequence, not a single intervention.','تدبير PPH سلسلة من الخطوات المنسقة وليس تدخلًا واحدًا.'] ]},
 pas:{emoji:'🩸',en:'Placenta Accreta Spectrum — Operative Planning',ar:'طيف التصاق المشيمة — التخطيط الجراحي',patient:'Rana',details:'36 y • G4P3 • 2 previous CS',refs:['ACOG Obstetric Care Consensus: Placenta Accreta Spectrum'],qs:[
['Risk','She has placenta previa and two previous cesareans; ultrasound is suspicious for PAS.','ما الخطوة الأهم؟',['Plan delivery with an experienced multidisciplinary team at an appropriately equipped center','Plan unassisted vaginal birth','Attempt manual placental removal at home','Ignore the ultrasound'],0,'Antenatal diagnosis and planned multidisciplinary care improve preparedness and outcomes.','التشخيص قبل الولادة والتخطيط متعدد الاختصاصات يحسنان الاستعداد والنتائج.'],
['Preparation','The planned delivery is being arranged.','ما الذي يجب تحضيره؟',['Experienced pelvic surgeons, obstetric anaesthesia, neonatology and robust blood-bank support','Only one operator','No blood preparation','Routine outpatient resources only'],0,'PAS can cause life-threatening haemorrhage and requires coordinated resources.','قد يسبب PAS نزفًا مهددًا للحياة ويحتاج موارد منسقة.'],
['Timing','She is stable with no bleeding or labor.','ما المبدأ؟',['Plan delivery before labor/bleeding in an experienced center according to the clinical plan','Wait for spontaneous labor routinely','Delay indefinitely','Schedule home delivery'],0,'Planned delivery before labor or bleeding is part of standard PAS planning.','الولادة المخططة قبل المخاض أو النزف جزء من التخطيط القياسي لـPAS.'],
['OR setup','The team enters theatre.','ما التحضير المهم؟',['Ensure blood products and massive-transfusion capability are readily available','Remove IV access','Avoid anaesthesia planning','Keep the blood bank uninformed'],0,'Blood-bank readiness is essential because major haemorrhage is a central risk.','جاهزية بنك الدم أساسية لأن النزف الشديد من المخاطر الرئيسية.'],
['Placenta','After fetal delivery, the placenta does not separate normally.','ما المبدأ؟',['Avoid forceful placental removal when PAS is suspected and follow the planned surgical strategy','Pull forcefully on the placenta','Give uterotonics and pull harder','Wait without a team'],0,'ACOG states that forced placental removal can cause profuse haemorrhage.','تذكر ACOG أن نزع المشيمة بالقوة قد يسبب نزفًا غزيرًا.'],
['Definitive approach','PAS is confirmed and the planned definitive operation is proceeding.','ما النهج المقبول عمومًا؟',['Cesarean hysterectomy with the placenta left in situ, when this is the planned appropriate approach','Routine manual extraction','Forceful curettage','Discharge after delivery'],0,'Cesarean hysterectomy with placenta left in situ is the generally accepted approach in many PAS cases.','القيصرية مع استئصال الرحم وترك المشيمة في مكانها هي النهج المقبول عمومًا في كثير من حالات PAS.'],
['Unexpected PAS','PAS is unexpectedly recognized after delivery in a stable patient.','ما التصرف؟',['Pause, alert anaesthesia and mobilize appropriate expertise/resources before proceeding when feasible','Immediately pull the placenta','Close without a plan and leave','Send the patient to recovery alone'],0,'When stable, pausing and mobilizing expertise/resources can reduce avoidable haemorrhage.','عند الاستقرار يمكن للتوقف واستدعاء الخبرات والموارد أن يقلل النزف القابل للتجنب.'],
['Bleeding','Major bleeding begins.','ما الأولوية؟',['Coordinate surgical haemorrhage control with anaesthesia, blood bank and critical care support','Focus only on the operative field','Stop transfusion planning','Wait for Hb tomorrow'],0,'Management requires continuous multidisciplinary coordination.','التدبير يحتاج تنسيقًا مستمرًا متعدد الاختصاصات.'],
['Safety','The surgeon proposes a technically difficult dissection beyond local expertise.','ما المبدأ؟',['Use the most experienced available team and consider transfer/stabilization when safe and feasible','Proceed regardless of expertise','Avoid senior input','Continue alone'],0,'ACOG emphasizes experienced teams and appropriate-level centers for PAS.','تؤكد ACOG أهمية الخبرة والمراكز المناسبة لمستوى خطورة PAS.'],
['Debrief','Which statement is most accurate?','أي عبارة أدق؟',['PAS is a high-risk condition where preparation, avoidance of placental disruption and coordinated haemorrhage planning are central','PAS is usually low risk','Manual removal is always safest','Blood preparation is optional'],0,'Preparation and avoidance of placental disruption are central principles.','التحضير وتجنب العبث بالمشيمة من المبادئ الأساسية.'] ]},
 cesarean:{emoji:'🚨',en:'Emergency Cesarean — Acute Fetal Compromise',ar:'القيصرية الإسعافية — اختلال حاد في حالة الجنين',patient:'Lina',details:'30 y • 39 weeks • labor',refs:['ACOG intrapartum fetal monitoring resources','Local emergency cesarean protocol'],qs:[
['Trace','A term patient develops persistent fetal bradycardia.','ما الأولوية؟',['Recognize the abnormal tracing, call for help and begin immediate maternal/fetal assessment and intrauterine resuscitative measures as appropriate','Leave the monitor','Wait 30 minutes','Discharge'],0,'Persistent bradycardia requires urgent assessment and escalation.','بطء القلب الجنيني المستمر يحتاج تقييمًا وتصعيدًا عاجلين.'],
['Reversible causes','The tracing remains abnormal.','ماذا تبحث عنه؟',['Reversible maternal/intrapartum causes while preparing for urgent delivery if indicated','Only the fetal sex','Routine outpatient causes','No cause'],0,'Rapidly reversible causes should be assessed while preparing definitive action.','يجب البحث سريعًا عن الأسباب القابلة للعكس مع التحضير للتدبير النهائي.'],
['Team','Bradycardia persists despite initial measures.','ما الخطوة؟',['Activate the emergency obstetric, anaesthetic and neonatal team','Wait for the next clinic','Send the patient home','Cancel monitoring'],0,'Persistent acute fetal compromise requires coordinated emergency response.','اختلال الجنين الحاد المستمر يحتاج استجابة إسعافية منسقة.'],
['Decision','There is no imminent vaginal delivery and the fetal status remains critical.','كيف تفكر؟',['Proceed to urgent operative delivery according to the clinical situation and local protocol','Continue observation indefinitely','Start an outpatient induction plan','Wait for tomorrow'],0,'When acute fetal compromise persists and vaginal birth is not imminent, urgent operative delivery may be indicated.','عندما يستمر اختلال الجنين ولا تكون الولادة المهبلية وشيكة قد تستطب الولادة الجراحية الإسعافية.'],
['Preparation','The patient is transferred to theatre.','ما الذي يجب أن يستمر؟',['Continuous communication, maternal monitoring and neonatal preparation','Stop maternal monitoring','Send neonatology away','Remove all IV access'],0,'Maternal safety and neonatal readiness continue throughout emergency delivery.','تستمر سلامة الأم والاستعداد للوليد طوال الولادة الإسعافية.'],
['Anaesthesia','Anaesthesia is assessing the patient.','ما المبدأ؟',['Choose the safest feasible anaesthetic approach based on urgency, maternal status and local expertise','Use one technique regardless of circumstances','Delay surgery for a preferred technique','Avoid anaesthesia review'],0,'Anaesthetic choice is individualized to urgency and maternal circumstances.','اختيار التخدير فردي بحسب الاستعجال وحالة الأم.'],
['Intraoperative change','Maternal BP falls during preparation.','ما الأولوية؟',['Reassess ABCs and treat maternal instability while maintaining the emergency delivery plan','Ignore BP','Stop all support','Wait for postpartum review'],0,'Maternal instability can worsen fetal status and requires immediate attention.','عدم استقرار الأم قد يزيد اختلال الجنين ويحتاج تدخلاً فوريًا.'],
['Outcome','Baby is delivered and the neonatal team begins assessment.','ما التالي؟',['Support neonatal transition and continue maternal assessment for bleeding and complications','Leave the mother unmonitored','Ignore uterine tone','End all documentation'],0,'Both maternal and neonatal reassessment are required after emergency cesarean.','يجب إعادة تقييم الأم والوليد بعد القيصرية الإسعافية.'],
['Debrief','Why was the decision time-critical?','لماذا كان القرار حساسًا للوقت؟',['Persistent acute fetal compromise can threaten fetal oxygenation, so delay must be minimized while maternal safety is maintained','Because all cesareans are emergencies','Because monitoring is unnecessary','Because surgery is always safer than vaginal birth'],0,'The emergency is driven by persistent fetal compromise and the risk of deterioration.','الاستعجال سببه اختلال الجنين المستمر وخطر التدهور.'],
['Final','What is the best overall principle?','ما المبدأ العام الأفضل؟',['Recognize deterioration early, communicate, address reversible causes and escalate promptly when indicated','Treat the monitor number alone','Ignore maternal status','Delay until the next shift'],0,'Good emergency care combines recognition, maternal assessment, team communication and timely definitive action.','الرعاية الإسعافية الجيدة تجمع التعرف المبكر وتقييم الأم والتواصل والتدبير النهائي في الوقت المناسب.'] ]}
};
const L={en:{title:'Advanced Surgical Levels',sub:'10 connected clinical decisions per case — your choices change the scenario.',start:'START SURGICAL CASE',next:'CONTINUE →',why:'WHY?',consequence:'Clinical consequence',correct:'Correct',incorrect:'Not optimal',score:'Score',health:'Patient health',finish:'CASE COMPLETE',refs:'Clinical references',home:'HOME'},ar:{title:'المستويات الجراحية المتقدمة',sub:'10 قرارات سريرية مترابطة في كل حالة — اختياراتك تغيّر مسار السيناريو.',start:'ابدأ الحالة الجراحية',next:'تابع ←',why:'لماذا؟',consequence:'النتيجة السريرية',correct:'صحيح',incorrect:'غير مثالي',score:'النقاط',health:'صحة المريضة',finish:'اكتملت الحالة',refs:'المراجع العلمية',home:'الرئيسية'}};
let lang='en',current=null,qi=0,score=0,health=100,errors=0,locked=false;const $=id=>document.getElementById(id);const tr=()=>L[lang];
function injectCards(){const grid=$('levelGrid');if(!grid||grid.dataset.advanced)return;grid.dataset.advanced='1';const wrap=document.createElement('div');wrap.className='advancedWrap';wrap.innerHTML=`<div class="advancedHead"><div><div class="eyebrow">${lang==='ar'?'🩺 جراحة وتوليد • مستوى متقدم':'🩺 SURGICAL OB/GYN • ADVANCED'}</div><h2 id="advTitle">${tr().title}</h2><p id="advSub">${tr().sub}</p></div></div><div class="advancedGrid">${Object.entries(A).map(([k,c],i)=>`<button class="advancedCard" data-adv="${k}"><span class="advIcon">${c.emoji}</span><span><b>${c[lang]}</b><small>${lang==='ar'?'10 قرارات مترابطة • صعوبة '+(i+3)+'/5':'10 connected decisions • Difficulty '+(i+3)+'/5'}</small></span><strong>→</strong></button>`).join('')}</div>`;grid.appendChild(wrap);grid.querySelectorAll('[data-adv]').forEach(b=>b.onclick=()=>start(b.dataset.adv));}
function show(id){['home','levels','game','end'].forEach(x=>$(x)?.classList.toggle('hidden',x!==id));}
function start(key){current=A[key];qi=0;score=0;health=100;errors=0;locked=false;show('game');renderQ();}
function renderQ(){const c=current,q=c.qs[qi];$('caseTag').textContent=`SURGICAL ${qi+1}/10`;$('caseTitle').textContent=c[lang];$('caseBrief').textContent=lang==='ar'?q[2]:q[1];$('patientName').textContent=c.patient;$('patientDetails').textContent=c.details;$('score').textContent=score;$('health').textContent=health;$('healthBar').style.width=health+'%';$('progress').textContent=`${qi+1} / 10`;$('choices').innerHTML=q[3].map((x,i)=>`<button class="choice advChoice" data-i="${i}">${String.fromCharCode(65+i)}. ${x}</button>`).join('');$('feedback').classList.add('hidden');$('nextBtn').classList.add('hidden');$('visualArt').innerHTML=`<div class="advancedMonitor"><b>❤️ HR</b><span>${health<50?'138':'112'}</span><b>🩸 BP</b><span>${health<50?'78/48':'104/68'}</span><b>🩸 EBL</b><span>${c===A.pphS?(health<60?'2500':'1200')+' mL':'—'}</span></div>`;$('choices').querySelectorAll('.advChoice').forEach(b=>b.onclick=()=>answer(+b.dataset.i));}
function answer(i){if(locked)return;locked=true;const q=current.qs[qi],correct=i===q[4],why=lang==='ar'?q[6]:q[5];const fb=$('feedback');if(correct){score+=10;fb.innerHTML=`<div class="fbGood">✅ ${tr().correct}</div><p><b>${tr().why}</b><br>${why}</p>`;}else{score=Math.max(0,score-5);health=Math.max(10,health-12);errors++;fb.innerHTML=`<div class="fbBad">⚠️ ${tr().incorrect}</div><p><b>${tr().consequence}</b><br>${lang==='ar'?'قد يؤدي هذا القرار إلى تأخير التدبير أو زيادة الخطر. أعد التفكير في الأولويات السريرية.':'This choice may delay definitive care or increase risk. Reconsider the clinical priorities.'}</p><p><b>${tr().why}</b><br>${why}</p>`;}$('score').textContent=score;$('health').textContent=health;$('healthBar').style.width=health+'%';$('feedback').classList.remove('hidden');$('choices').querySelectorAll('button').forEach((b,n)=>{b.disabled=true;if(n===q[4])b.classList.add('correct');if(n===i&&!correct)b.classList.add('wrong');});$('nextBtn').textContent=qi===9?tr().finish:tr().next;$('nextBtn').classList.remove('hidden');}
function next(){if(!locked)return;if(qi<9){qi++;locked=false;renderQ();}else finish();}
function finish(){show('end');$('finalScore').textContent=score;$('correctCount').textContent=(10-errors)+'/10';$('errorCount').textContent=errors;$('finalHealth').textContent=health+'%';$('endMessage').textContent=score>=85?'🔥 Excellent clinical prioritization!':score>=65?'👏 Good work. Review the missed decisions and try again.':'Keep practicing — prioritize recognition, safety and escalation.';$('clinicalRefs').innerHTML=`<div class="references"><h3>${tr().refs}</h3>${current.refs.map(r=>`<span>${r}</span>`).join('')}</div>`;}
function bind(){document.addEventListener('click',e=>{if(e.target.closest('#nextBtn'))next();if(e.target.closest('#quitBtn'))show('levels');if(e.target.closest('#levelsBtn'))show('levels');if(e.target.closest('#backHome'))show('home');});$('langBtn')?.addEventListener('click',()=>{lang=lang==='en'?'ar':'en';document.documentElement.lang=lang;setTimeout(()=>{const w=document.querySelector('.advancedWrap');if(w){w.querySelector('#advTitle').textContent=tr().title;w.querySelector('#advSub').textContent=tr().sub;w.querySelectorAll('[data-adv]').forEach(b=>{const c=A[b.dataset.adv];b.querySelector('b').textContent=c[lang];b.querySelector('small').textContent=lang==='ar'?'10 قرارات مترابطة':'10 connected decisions';});}if(current)renderQ();},0);});new MutationObserver(injectCards).observe($('levels'),{attributes:true,attributeFilter:['class']});injectCards();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();