(() => {
'use strict';

const LEVELS = [
  {
    id:'ectopic', emoji:'🚨', en:'Ruptured Ectopic Pregnancy', ar:'الحمل الهاجر المتمزق', patient:'Sara', detailsEn:'28 years • 7 weeks pregnant', detailsAr:'28 سنة • حمل 7 أسابيع',
    refs:['NICE NG126 — Ectopic pregnancy and miscarriage'],
    steps:[
      ['Arrival','A 28-year-old pregnant patient arrives with severe unilateral lower abdominal pain, vaginal bleeding and dizziness.','وصلت مريضة حامل بعمر 28 سنة مع ألم شديد أحادي الجانب أسفل البطن ونزف مهبلي ودوخة.','What do you do FIRST?','ما أول شيء تفعله؟',['Assess ABCs and haemodynamic stability','Ask for a routine appointment','Wait for serial β-hCG before assessing her','Give methotrexate immediately'],0,'An unstable or potentially unstable patient needs immediate assessment and resuscitation; do not delay life-saving care.','المريضة غير المستقرة أو المعرّضة لعدم الاستقرار تحتاج إلى تقييم وإنعاش فوريين؛ لا تؤخر التدبير المنقذ للحياة.','assessment'],
      ['History','She reports increasing pain, near-syncope and vaginal bleeding.','تذكر ازدياد الألم وقرب الإغماء والنزف المهبلي.','Which history point is most urgent to clarify?','ما المعلومة من القصة المرضية التي يجب توضيحها بشكل عاجل؟',['Amount of bleeding and symptoms of collapse','Favourite food','Childhood vaccination history','Last dental visit'],0,'Bleeding and symptoms suggesting haemodynamic compromise directly affect urgency and escalation.','كمية النزف وأعراض الانهيار الدوري تؤثر مباشرة في درجة الاستعجال والحاجة للتصعيد.','history'],
      ['Vitals','BP 82/50, HR 128, SpO₂ 97%. She is pale and dizzy.','الضغط 82/50، النبض 128، وإشباع الأكسجين 97%. تبدو شاحبة ودوخة واضحة.','How do you interpret this?','كيف تفسر هذه المعطيات؟',['Haemodynamic instability','Stable because SpO₂ is normal','Normal early pregnancy physiology','No urgent action is needed'],0,'Hypotension with marked tachycardia and symptoms is concerning for haemodynamic instability.','انخفاض الضغط مع تسرع القلب والأعراض يتوافق مع عدم الاستقرار الديناميكي الدموي.','vitals'],
      ['Access','The team is called and resuscitation is beginning.','تم استدعاء الفريق وبدأ الإنعاش.','What practical step should happen early?','ما الخطوة العملية التي ينبغي إجراؤها مبكرًا؟',['Establish appropriate IV access and send urgent blood tests/crossmatch according to local protocol','Delay access until ultrasound is completed','Send her home','Start oral iron'],0,'Early access and preparation for blood support are part of resuscitation in a bleeding unstable patient.','تأمين الوصول الوريدي المناسب والتحضير للدم جزء من الإنعاش لدى المريضة النازفة غير المستقرة.','resuscitation'],
      ['Imaging','Pregnancy test is positive. Ultrasound shows no intrauterine pregnancy and free fluid.','اختبار الحمل إيجابي. الإيكو لا يظهر حملًا داخل الرحم مع وجود سائل حر.','What is the most likely diagnosis?','ما التشخيص الأكثر احتمالًا؟',['Ruptured ectopic pregnancy','Normal early pregnancy','Placenta previa','Hyperemesis gravidarum'],0,'The clinical picture plus free fluid in an unstable early pregnancy is highly concerning for rupture.','الصورة السريرية مع السائل الحر لدى حامل مبكر غير مستقر تثير الشك بقوة بتمزق الحمل الهاجر.','investigation'],
      ['Priority','She remains hypotensive despite initial measures.','لا تزال المريضة منخفضة الضغط رغم الإجراءات الأولية.','What should guide your next decision?','ما الذي يجب أن يوجّه قرارك التالي؟',['Her current haemodynamic status and need for definitive control','Waiting for a perfect set of laboratory results','The fact that she is only 7 weeks pregnant','Whether she prefers outpatient follow-up'],0,'Current instability and suspected rupture make definitive management time-critical.','عدم الاستقرار الحالي والاشتباه بالتمزق يجعلان التدبير النهائي حساسًا للوقت.','reassessment'],
      ['Team','The theatre team is available.','فريق غرفة العمليات متاح.','Who should be involved now?','من يجب إشراكه الآن؟',['Appropriate surgical, anaesthetic and transfusion support','Only the receptionist','No one until tomorrow','Only a radiologist'],0,'Major bleeding requires coordinated multidisciplinary preparation.','النزف المهم يحتاج إلى تحضير منسق متعدد الاختصاصات.','team'],
      ['Decision','The patient is unstable and rupture is suspected.','المريضة غير مستقرة والتمزق مشتبه به.','What is the best overall direction?','ما التوجه العام الأفضل؟',['Urgent operative management while resuscitation continues','Methotrexate and outpatient observation','Wait for serial β-hCG','Discharge if pain improves briefly'],0,'Suspected rupture with haemodynamic instability requires urgent operative management alongside resuscitation.','الاشتباه بالتمزق مع عدم الاستقرار يتطلب تدبيرًا جراحيًا إسعافيًا بالتوازي مع الإنعاش.','decision'],
      ['Reassess','Before transfer, BP improves to 96/60 but she remains tachycardic.','قبل النقل تحسن الضغط إلى 96/60 لكن ما زال النبض متسرعًا.','What should you do?','ماذا تفعل؟',['Continue close reassessment and resuscitation while proceeding with definitive care','Cancel the emergency because BP improved once','Stop monitoring','Send her home'],0,'Transient improvement does not remove the risk from active bleeding.','التحسن العابر لا يلغي خطر النزف المستمر.','reassessment'],
      ['Debrief','The patient reaches theatre with the team prepared.','وصلت المريضة إلى غرفة العمليات والفريق جاهز.','Which principle best summarizes the case?','أي مبدأ يلخص الحالة بشكل أفضل؟',['Stabilize, recognize rupture early, mobilize the team and avoid dangerous delay','Wait for every test before acting','Treat the scan rather than the patient','Use medication alone in an unstable rupture'],0,'The key learning point is rapid recognition, resuscitation, multidisciplinary escalation and definitive management.','النقطة التعليمية الأساسية هي التعرف المبكر والإنعاش والتصعيد متعدد الاختصاصات والتدبير النهائي.','debrief']
    ]
  },
  {
    id:'normalbirth', emoji:'👶', en:'Normal Vaginal Birth', ar:'الولادة المهبلية الطبيعية', patient:'Maya', detailsEn:'25 years • 39+2 weeks • active labour', detailsAr:'25 سنة • 39+2 أسبوع • مخاض فعال',
    refs:['NICE NG235 — Intrapartum care'],
    steps:[
      ['Arrival','Healthy term patient in active labour; observations and fetal assessment are reassuring.','مريضة سليمة بتمام الحمل في مخاض فعال؛ العلامات الحيوية وتقييم الجنين مطمئنان.','What is your first approach?','ما نهجك الأول؟',['Support labour and continue appropriate maternal/fetal assessment','Immediate caesarean birth','Stop all monitoring','Give magnesium sulfate routinely'],0,'Uncomplicated labour is supported with ongoing assessment and shared decision-making.','في المخاض غير المعقد نستمر بالدعم والتقييم المناسب ومشاركة القرار.','assessment'],
      ['History','She is coping well and contractions are regular.','تتعامل مع الألم جيدًا والتقلصات منتظمة.','What should you clarify before deciding on an intervention?','ما الذي يجب توضيحه قبل اتخاذ قرار بالتدخل؟',['Her symptoms, preferences and progress of labour','Her favourite colour','Her childhood illnesses only','No further information'],0,'Clinical decisions should integrate progress, maternal/fetal condition and patient preferences.','يجب أن تراعي القرارات تقدم المخاض وحالة الأم والجنين وتفضيلات المريضة.','history'],
      ['Assessment','FHR remains reassuring and maternal observations are stable.','ما زال نبض الجنين مطمئنًا والعلامات الحيوية للأم مستقرة.','What is the most appropriate next step?','ما الخطوة التالية الأنسب؟',['Continue supportive care and appropriate monitoring','Perform emergency caesarean birth','Apply fundal pressure','Stop assessing the fetus'],0,'There is no indication for unnecessary intervention when labour is progressing safely.','لا يوجد داعٍ لتدخل غير ضروري عندما يتقدم المخاض بأمان.','assessment'],
      ['Second stage','The fetal head is crowning and the mother is pushing effectively.','رأس الجنين يتوج والأم تدفع بفعالية.','What should you prioritize?','ما الأولوية؟',['Support controlled birth and monitor mother and baby','Forcefully pull on the head','Routine fundal pressure','Leave the room'],0,'Supportive, controlled birth with ongoing assessment is appropriate.','الدعم والولادة المضبوطة مع استمرار التقييم هما النهج المناسب.','management'],
      ['Birth','The baby is born breathing and crying.','وُلد الطفل ويتنفس ويبكي.','What should happen next?','ماذا تفعل بعد ذلك؟',['Assess the newborn and support appropriate skin-to-skin care while monitoring the mother','Separate mother and baby routinely','Ignore uterine tone','Stop all maternal observations'],0,'Newborn assessment and maternal observation remain important immediately after birth.','يبقى تقييم الوليد ومراقبة الأم مهمين مباشرة بعد الولادة.','postpartum'],
      ['Third stage','The placenta is delivered; uterus is firm and blood loss is minimal.','خرجت المشيمة والرحم متماسك والنزف قليل.','What should guide your next step?','ما الذي يوجه خطوتك التالية؟',['Continue postpartum observation and assess bleeding and uterine tone','Discharge immediately','Order CT routinely','Stop monitoring'],0,'Routine postpartum observation detects early deterioration.','المراقبة بعد الولادة تساعد على اكتشاف التدهور المبكر.','reassessment'],
      ['Change','Bleeding increases and the uterus feels less firm.','ازداد النزف وأصبح الرحم أقل تماسكًا.','What should you do first?','ماذا تفعل أولًا؟',['Recognize possible postpartum haemorrhage, call for help and assess the cause','Ignore the change','Wait one hour','Discharge the patient'],0,'A change in bleeding and uterine tone requires prompt assessment and escalation.','تغير النزف وتوتر الرحم يحتاج تقييمًا وتصعيدًا سريعًا.','deterioration'],
      ['Team','The bleeding continues.','استمر النزف.','What is an appropriate team response?','ما الاستجابة المناسبة من الفريق؟',['Activate appropriate help and begin structured PPH assessment/resuscitation','Ask only the patient to monitor herself','Delay calling anyone','Move the patient home'],0,'PPH is time-critical and requires coordinated response.','نزف ما بعد الولادة حساس للوقت ويحتاج استجابة منسقة.','team'],
      ['Safety','The uterus becomes firm and bleeding decreases after appropriate initial management.','أصبح الرحم متماسكًا وانخفض النزف بعد التدبير الأولي المناسب.','What should you do now?','ماذا تفعل الآن؟',['Continue reassessment rather than assuming the problem is over','Stop monitoring immediately','Discharge without review','Start unnecessary imaging'],0,'Improvement should be confirmed with ongoing observation.','يجب تأكيد التحسن باستمرار المراقبة وإعادة التقييم.','reassessment'],
      ['Debrief','The patient and newborn remain stable after observation.','بقيت الأم والوليد مستقرين بعد المراقبة.','What is the key lesson?','ما الدرس الأساسي؟',['Normal birth still requires structured observation and readiness to recognize deterioration','Normal labour needs no monitoring','Every labour should end in caesarean birth','Interventions should be used routinely'],0,'Good obstetric care balances support for normal birth with vigilance for complications.','الرعاية التوليدية الجيدة توازن بين دعم الولادة الطبيعية واليقظة لاكتشاف المضاعفات.','debrief']
    ]
  },
  {
    id:'preeclampsia', emoji:'⚡', en:'Preeclampsia / Eclampsia', ar:'مقدمات الارتعاج / الإرجاج', patient:'Lina', detailsEn:'31 years • 35 weeks • severe headache', detailsAr:'31 سنة • 35 أسبوع • صداع شديد',
    refs:['ACOG — Gestational Hypertension and Preeclampsia','NICE NG133 — Hypertension in pregnancy'],
    steps:[
      ['Red flag','BP 170/112 with severe headache and visual symptoms at 35 weeks.','الضغط 170/112 مع صداع شديد وأعراض بصرية بعمر حمل 35 أسبوعًا.','What do you do FIRST?','ما أول شيء تفعله؟',['Recognize severe hypertension and urgently assess and stabilize','Send her home to rest','Wait until tomorrow','Give only oral fluids'],0,'Severe-range hypertension with neurologic symptoms is a maternal emergency.','ارتفاع الضغط ضمن المجال الشديد مع أعراض عصبية حالة إسعافية عند الأم.','assessment'],
      ['History','She reports worsening headache and flashing lights.','تذكر ازدياد الصداع ورؤية ومضات ضوئية.','Which question matters most now?','أي سؤال أهم الآن؟',['Ask about neurological symptoms and other severe features','Ask about her favourite meal','Ask about childhood vaccinations','Ask about dental history'],0,'Symptoms suggesting severe disease influence urgency and management.','الأعراض التي تشير إلى مرض شديد تؤثر في الاستعجال والتدبير.','history'],
      ['Vitals','Repeat BP remains 168/110.','بقي الضغط 168/110 عند إعادة القياس.','How should this influence your plan?','كيف يؤثر ذلك في الخطة؟',['Treat severe hypertension urgently according to protocol','Wait for a routine clinic appointment','Ignore the repeat value','Give magnesium sulfate as a substitute for BP treatment'],0,'Persistent severe-range BP requires urgent antihypertensive treatment according to protocol; magnesium sulfate does not replace BP control.','استمرار الضغط ضمن المجال الشديد يحتاج خفضًا عاجلًا وفق البروتوكول؛ مغنزيوم سلفات لا يحل محل علاج الضغط.','vitals'],
      ['Investigation','The team is assessing maternal and fetal status.','الفريق يقيّم حالة الأم والجنين.','What information is useful?','ما المعلومات المفيدة؟',['Maternal labs and fetal assessment guided by the clinical picture','Only a routine dental X-ray','No further assessment','Wait until postpartum'],0,'Assessment should look for maternal organ involvement and fetal wellbeing.','يجب تقييم إصابة أعضاء الأم وحالة الجنين.','investigation'],
      ['Seizure prevention','She has severe preeclampsia with neurological symptoms.','لديها مقدمات ارتعاج شديدة مع أعراض عصبية.','Which therapy is used for seizure prophylaxis when indicated?','ما العلاج المستخدم للوقاية من الاختلاجات عند الاستطباب؟',['Magnesium sulfate','Methotrexate','Oxytocin','Warfarin'],0,'Magnesium sulfate is used for seizure prophylaxis in severe preeclampsia and treatment of eclampsia according to protocol.','يستخدم مغنزيوم سلفات للوقاية من الاختلاجات في مقدمات الارتعاج الشديدة ولعلاج الإرجاج وفق البروتوكول.','management'],
      ['Seizure','She suddenly develops a generalized seizure.','أصيبت فجأة باختلاج معمّم.','What is the immediate priority?','ما الأولوية الفورية؟',['Protect safety, support airway/ABCs, call for help and treat eclampsia according to protocol','Forcefully restrain her','Put an object in her mouth','Leave her alone'],0,'Safety, ABC support, help and magnesium sulfate are central to eclampsia management.','سلامة المريضة ودعم ABC واستدعاء المساعدة ومغنزيوم سلفات عناصر أساسية في تدبير الإرجاج.','deterioration'],
      ['Reassess','After seizure treatment she is drowsy but breathing adequately.','بعد علاج الاختلاج أصبحت نعسانة لكنها تتنفس بشكل كافٍ.','What should you do?','ماذا تفعل؟',['Continue close maternal monitoring and reassess airway, breathing and neurological status','Assume she is cured and discharge her','Stop monitoring','Give oral fluids only'],0,'Post-seizure reassessment is essential because deterioration can recur.','إعادة تقييم الأم بعد الاختلاج ضرورية لأن التدهور قد يتكرر.','reassessment'],
      ['Team','The maternal condition is stabilized enough for planning.','أصبحت حالة الأم مستقرة بما يكفي للتخطيط.','Who should be involved?','من يجب إشراكه؟',['Senior obstetric, anaesthetic and neonatal teams as appropriate','No team until discharge','Only a receptionist','Only a laboratory technician'],0,'Severe disease and possible urgent birth require coordinated multidisciplinary care.','المرض الشديد واحتمال الولادة العاجلة يحتاجان رعاية متعددة الاختصاصات.','team'],
      ['Delivery','Maternal stabilization has been achieved and the team reviews the whole clinical picture.','تم تثبيت الأم والفريق يراجع الصورة السريرية كاملة.','What is the correct principle?','ما المبدأ الصحيح؟',['Plan delivery based on maternal/fetal status after stabilization','Delay all delivery decisions regardless of condition','Treat only the headache','Discharge after the seizure'],0,'Delivery timing and mode depend on the clinical situation; stabilization comes first in an emergency.','توقيت وطريقة الولادة يعتمدان على الحالة السريرية؛ تثبيت الأم يأتي أولًا في الطوارئ.','decision'],
      ['Debrief','The team completes the emergency plan.','أكمل الفريق خطة الطوارئ.','What is the key learning point?','ما النقطة التعليمية الأساسية؟',['Recognize severe disease, control BP urgently, prevent/treat seizures and coordinate delivery after stabilization','Use magnesium sulfate instead of BP treatment','Wait for symptoms to disappear at home','Focus only on the fetus'],0,'The sequence is recognition, maternal stabilization, seizure prevention/treatment, monitoring and appropriate delivery planning.','التسلسل هو التعرف على الحالة وتثبيت الأم وخفض الضغط والوقاية/العلاج من الاختلاجات والمراقبة والتخطيط المناسب للولادة.','debrief']
    ]
  },
  {
    id:'pph', emoji:'🩸', en:'Postpartum Hemorrhage', ar:'نزف ما بعد الولادة', patient:'Nour', detailsEn:'29 years • 20 min after vaginal birth', detailsAr:'29 سنة • بعد 20 دقيقة من الولادة المهبلية',
    refs:['WHO — Consolidated guidelines for prevention, diagnosis and treatment of postpartum haemorrhage (2025)'],
    steps:[
      ['Alarm','Heavy vaginal bleeding begins 20 minutes after birth. She is pale and tachycardic.','بدأ نزف مهبلي غزير بعد 20 دقيقة من الولادة. المريضة شاحبة ومتسرعة النبض.','What do you do FIRST?','ما أول شيء تفعله؟',['Call for help, assess ABCs, quantify blood loss and start resuscitation','Wait 30 minutes','Discharge her','Give analgesia only'],0,'PPH is time-critical: escalate, resuscitate, quantify bleeding and identify the cause.','نزف ما بعد الولادة حساس للوقت: صعّد التدبير، ابدأ الإنعاش، قِس النزف وحدد السبب.','assessment'],
      ['Cause','The uterus feels boggy and enlarged.','الرحم رخو ومتضخم.','What is the most likely cause?','ما السبب الأكثر احتمالًا؟',['Uterine atony','Ectopic pregnancy','Hyperemesis','Placenta previa before birth'],0,'A boggy uterus after birth strongly suggests uterine atony.','الرحم الرخو بعد الولادة يشير بقوة إلى وهن الرحم.','examination'],
      ['Resuscitation','Bleeding continues and BP is falling.','استمر النزف وبدأ الضغط بالانخفاض.','What should happen alongside cause-directed treatment?','ما الذي يجب أن يحدث بالتوازي مع علاج السبب؟',['Ongoing resuscitation, monitoring and preparation for blood products as indicated','Stop monitoring','Wait for bleeding to stop','Give oral iron'],0,'Resuscitation and bleeding control proceed in parallel.','يستمر الإنعاش والسيطرة على النزف بالتوازي.','resuscitation'],
      ['First-line','Atony is suspected.','يشتبه بوهن الرحم.','Which immediate approach is appropriate?','ما النهج الفوري المناسب؟',['Uterine massage and uterotonic treatment according to protocol','Wait for CT before acting','Methotrexate','Discharge'],0,'Uterine massage and uterotonics are key components for atony while resuscitation continues.','تدليك الرحم والقابضات الرحمية من التدابير الأساسية لوهن الرحم مع استمرار الإنعاش.','management'],
      ['TXA','PPH is clinically diagnosed and bleeding continues.','تم تشخيص النزف سريريًا واستمر النزف.','What additional treatment should be considered early?','ما العلاج الإضافي الذي ينبغي التفكير به مبكرًا؟',['IV tranexamic acid as soon as possible and within 3 hours of birth according to protocol','Methotrexate','Wait until tomorrow','Stop resuscitation'],0,'WHO recommends early IV TXA for clinically diagnosed PPH, as soon as possible and within 3 hours of birth, in addition to standard care.','توصي منظمة الصحة العالمية بالترانيكساميك الوريدي مبكرًا عند تشخيص النزف، بأسرع ما يمكن وخلال 3 ساعات من الولادة، إضافة إلى الرعاية القياسية.','management'],
      ['Reassess','After initial measures, blood loss remains substantial.','بعد التدابير الأولية ما زال النزف كبيرًا.','What should guide escalation?','ما الذي يجب أن يوجه التصعيد؟',['Ongoing blood loss, haemodynamics and response to treatment','A single normal SpO₂ reading','Waiting for the next day','Ignoring the trend'],0,'Escalation depends on the clinical trajectory and response, not one isolated number.','يعتمد التصعيد على مسار الحالة والاستجابة للعلاج وليس على رقم منفرد.','reassessment'],
      ['Team','The haemorrhage is not controlled.','لم تتم السيطرة على النزف.','Who should be mobilized?','من يجب استدعاؤه؟',['Senior obstetric, anaesthetic, theatre and transfusion support','Only outpatient reception','No one','Only a radiologist'],0,'Major PPH requires multidisciplinary escalation.','النزف الشديد يحتاج تصعيدًا متعدد الاختصاصات.','team'],
      ['Escalation','Bleeding persists despite initial medical management.','استمر النزف رغم التدبير الطبي الأولي.','What is the next principle?','ما المبدأ التالي؟',['Rapidly escalate to definitive bleeding control and surgical/interventional options as appropriate','Continue the same step indefinitely','Send the patient home','Stop blood preparation'],0,'Persistent bleeding requires definitive control without dangerous delay.','النزف المستمر يحتاج السيطرة النهائية دون تأخير خطير.','surgical'],
      ['Coagulopathy','The patient continues to bleed and laboratory results are becoming abnormal.','استمر النزف وبدأت نتائج التحاليل بالتدهور.','What should you do?','ماذا تفعل؟',['Continue coordinated resuscitation and correct haemostatic problems according to protocol','Ignore the results','Stop transfusion planning','Wait for spontaneous recovery'],0,'Severe haemorrhage can cause coagulopathy; resuscitation and haemostatic support must be coordinated.','النزف الشديد قد يسبب اعتلال التخثر؛ يجب تنسيق الإنعاش والدعم الدموي وتصحيح اضطرابات الإرقاء وفق البروتوكول.','labs'],
      ['Debrief','Bleeding is controlled after timely escalation.','تمت السيطرة على النزف بعد التصعيد في الوقت المناسب.','What is the key lesson?','ما الدرس الأساسي؟',['Early recognition, structured resuscitation, cause identification and timely escalation save lives','Treat the number on the monitor only','Wait for imaging before every action','Use one drug as the whole treatment'],0,'PPH care is a time-critical bundle, not a single intervention.','تدبير النزف بعد الولادة حزمة تدخلات حساسة للوقت وليس تدخلاً دوائيًا واحدًا.','debrief']
    ]
  },
  {
    id:'shoulder', emoji:'🧑‍🍼', en:'Shoulder Dystocia', ar:'عسر ولادة الكتف', patient:'Hala', detailsEn:'30 years • term • head delivered', detailsAr:'30 سنة • تمام الحمل • خرج الرأس',
    refs:['RCOG Green-top Guideline No.42 — Shoulder Dystocia'],
    steps:[
      ['Recognition','The head delivers but retracts against the perineum and the shoulders do not deliver with gentle traction.','خرج الرأس لكنه تراجع باتجاه العجان ولم تخرج الكتفين مع الشد اللطيف.','What is happening?','ماذا يحدث؟',['Shoulder dystocia','Normal delivery','Placental abruption','Eclampsia'],0,'Failure of the shoulders to deliver after the head despite gentle traction is consistent with shoulder dystocia.','عدم ولادة الكتفين بعد الرأس رغم الشد اللطيف يتوافق مع عسر ولادة الكتف.','assessment'],
      ['Call','Shoulder dystocia is recognized.','تم التعرف على عسر ولادة الكتف.','What should you do immediately?','ماذا تفعل فورًا؟',['Call for help, announce the emergency and avoid excessive traction','Pull harder on the head','Leave the patient','Wait'],0,'Early communication and avoiding excessive traction are essential.','التواصل المبكر وتجنب الشد المفرط أمران أساسيان.','team'],
      ['First manoeuvre','The team is ready.','الفريق جاهز.','Which manoeuvre is appropriate early?','أي مناورة مناسبة مبكرًا؟',['McRoberts manoeuvre with suprapubic pressure as appropriate','Fundal pressure','Forceful downward traction','Routine episiotomy alone'],0,'McRoberts is a key first-line manoeuvre; suprapubic pressure may be added. Fundal pressure should not be used.','ماكروبرتس من المناورات الأساسية الأولى، ويمكن إضافة الضغط فوق العانة. ويجب عدم استخدام الضغط على قاع الرحم.','maneuver'],
      ['Reassess','The first manoeuvre has not released the shoulders.','لم تحرر المناورة الأولى الكتفين.','What should guide the next step?','ما الذي يجب أن يوجه الخطوة التالية؟',['Proceed systematically through appropriate additional manoeuvres with experienced help','Repeat forceful head traction','Apply fundal pressure','Stop all action'],0,'A systematic sequence reduces delay and injury.','التسلسل المنهجي يقلل التأخير والإصابة.','reassessment'],
      ['Communication','The team is becoming crowded around the bed.','بدأ الفريق يزدحم حول السرير.','What is useful?','ما المفيد؟',['Clear role allocation and closed-loop communication','Everyone acting independently','No verbal communication','Sending the neonatal team away'],0,'Team coordination is critical in a time-critical obstetric emergency.','تنسيق الفريق مهم جدًا في طوارئ التوليد الحساسة للوقت.','team'],
      ['Traction','The shoulder remains impacted.','لا يزال الكتف عالقًا.','Which approach should be avoided?','أي نهج يجب تجنبه؟',['Excessive traction on the fetal head','Systematic manoeuvres','Calling experienced help','Maternal repositioning'],0,'Excessive traction can increase brachial plexus injury risk.','الشد المفرط قد يزيد خطر أذية الضفيرة العضدية.','safety'],
      ['Birth','An additional manoeuvre releases the shoulders.','حررت مناورة إضافية الكتفين.','What is the immediate priority after birth?','ما الأولوية بعد الولادة؟',['Assess the newborn and mother for complications','Stop all monitoring','Assume no injury','Discharge immediately'],0,'Both newborn and mother require assessment after shoulder dystocia.','يجب تقييم الوليد والأم بعد عسر ولادة الكتف.','postpartum'],
      ['Neonatal','The newborn has reduced movement of one arm.','لدى الوليد نقص في حركة أحد الذراعين.','What should you do?','ماذا تفعل؟',['Prompt neonatal assessment for possible birth injury','Ignore it because the baby is breathing','Force the arm into position','Discharge'],0,'Reduced limb movement requires assessment for birth injury.','نقص حركة الطرف يحتاج تقييمًا لاحتمال وجود أذية ولادية.','neonatal'],
      ['Maternal','The mother has increased bleeding after birth.','زاد النزف لدى الأم بعد الولادة.','What should happen?','ماذا تفعل؟',['Assess and manage postpartum haemorrhage while continuing maternal observation','Ignore the bleeding','Focus only on the newborn','Discharge'],0,'Shoulder dystocia can be associated with maternal complications including PPH.','قد يرتبط عسر ولادة الكتف بمضاعفات أمومية منها نزف ما بعد الولادة.','maternal'],
      ['Debrief','Both patients are stable after assessment.','استقرت حالة الأم والوليد بعد التقييم.','What is the key learning point?','ما الدرس الأساسي؟',['Recognize early, call for help, use systematic manoeuvres, avoid excessive traction and assess complications','Pull harder when the shoulders are stuck','Use fundal pressure','Treat only the baby'],0,'Shoulder dystocia is a structured emergency requiring teamwork, appropriate manoeuvres and post-event assessment.','عسر ولادة الكتف طارئ منهجي يحتاج العمل الجماعي والمناورات المناسبة وتقييم المضاعفات بعد الولادة.','debrief']
    ]
  },
  {
    id:'or', emoji:'🔪', en:'Operating Room — Obstetric Surgical Emergency', ar:'غرفة العمليات — طوارئ جراحية توليدية', patient:'Rana', detailsEn:'34 years • emergency caesarean • major bleeding', detailsAr:'34 سنة • قيصرية إسعافية • نزف كبير',
    refs:['ACOG — Placenta Accreta Spectrum','WHO — Postpartum haemorrhage guideline'],
    steps:[
      ['OR arrival','You enter theatre for an emergency caesarean. The patient has major vaginal bleeding and BP 88/54.','دخلت غرفة العمليات لقيصرية إسعافية. لدى المريضة نزف كبير وضغط 88/54.','What is your FIRST priority?','ما أولويتك الأولى؟',['Coordinate anaesthetic resuscitation, assess haemodynamics and activate haemorrhage support','Start skin closure','Wait for a routine laboratory review','Send the patient back to the ward'],0,'The unstable patient requires simultaneous resuscitation, monitoring and surgical preparation.','المريضة غير المستقرة تحتاج إنعاشًا ومراقبة وتحضيرًا جراحيًا بالتوازي.','assessment'],
      ['Team','The anaesthetist reports worsening tachycardia.','أفاد طبيب التخدير بتفاقم تسرع القلب.','Who should be actively involved?','من يجب أن يكون مشاركًا بفعالية؟',['Senior obstetric surgeon, anaesthesia, theatre staff, neonatal team and blood bank as appropriate','Only one surgeon','No additional team','Only the laboratory'],0,'Major obstetric haemorrhage is a team emergency.','النزف التوليدي الكبير طارئ جماعي يحتاج فريقًا متعدد الاختصاصات.','team'],
      ['Blood','Estimated blood loss is rising rapidly.','تقدير فقد الدم يزداد بسرعة.','What should you request/confirm early?','ماذا تطلب أو تتأكد منه مبكرًا؟',['Appropriate blood availability/crossmatch and ongoing haemorrhage resuscitation according to protocol','Routine outpatient blood test only','No blood preparation','Wait until closure'],0,'Early blood preparation is essential when major haemorrhage is anticipated.','التحضير المبكر للدم أساسي عند توقع النزف الكبير.','resuscitation'],
      ['Findings','At surgery, the placenta appears abnormally adherent and separation is difficult.','أثناء الجراحة تبدو المشيمة ملتصقة بشكل غير طبيعي ويصعب فصلها.','What should you avoid?','ماذا يجب أن تتجنب؟',['Forceful attempts to remove an abnormally adherent placenta','Calling senior help','Maintaining resuscitation','Assessing blood loss'],0,'In suspected PAS, forceful placental removal can precipitate catastrophic haemorrhage.','عند الاشتباه بطيف التصاق المشيمة قد يؤدي نزع المشيمة بالقوة إلى نزف كارثي.','safety'],
      ['Decision','The team suspects placenta accreta spectrum and bleeding is significant.','يشتبه الفريق بطيف التصاق المشيمة والنزف مهم.','What principle should guide management?','ما المبدأ الذي يجب أن يوجه التدبير؟',['Use a planned multidisciplinary strategy appropriate to the situation rather than forceful placental separation','Remove the placenta forcefully at all costs','Stop blood preparation','Wait without senior involvement'],0,'PAS management requires coordinated multidisciplinary planning and avoidance of traumatic placental separation.','تدبير طيف التصاق المشيمة يحتاج تخطيطًا متعدد الاختصاصات وتجنب فصل المشيمة الرضحي.','surgical'],
      ['Reassess','BP falls to 74/42 and blood loss continues.','انخفض الضغط إلى 74/42 واستمر النزف.','What should you do?','ماذا تفعل؟',['Escalate haemorrhage resuscitation and definitive surgical control without delay','Pause all treatment for 30 minutes','Stop monitoring','Continue as if stable'],0,'Deterioration demands immediate escalation of resuscitation and bleeding control.','التدهور يحتاج تصعيدًا فوريًا للإنعاش والسيطرة على النزف.','deterioration'],
      ['Surgical planning','The senior team discusses definitive control.','يناقش الفريق الخبير السيطرة النهائية.','What should the decision be based on?','على ماذا يجب أن يعتمد القرار؟',['Extent of disease, haemodynamic status, bleeding, fertility considerations and local expertise/protocol','Only the clock','Only the patient age','A fixed operation for every patient'],0,'Surgical strategy depends on the clinical situation and expertise; no single procedure fits every emergency.','تعتمد الاستراتيجية الجراحية على الحالة السريرية وخبرة الفريق؛ لا توجد عملية واحدة تناسب كل طارئ.','decision'],
      ['Anaesthesia','The anaesthetist reports ongoing instability.','أفاد طبيب التخدير باستمرار عدم الاستقرار.','What should happen concurrently?','ماذا يجب أن يحدث بالتوازي؟',['Continue coordinated haemodynamic and blood-product management while surgery proceeds','Stop communication with anaesthesia','Wait for surgery to finish','Give oral fluids'],0,'Anaesthesia and surgery must work in parallel during major haemorrhage.','يجب أن يعمل التخدير والجراحة بالتوازي أثناء النزف الكبير.','team'],
      ['End point','Bleeding is finally controlled.','تمت السيطرة على النزف أخيرًا.','What is the next priority?','ما الأولوية التالية؟',['Reassess haemodynamics, ongoing bleeding, laboratory/haemostatic status and postoperative plan','Close the case and stop all monitoring','Discharge immediately','Ignore the blood loss'],0,'Control of bleeding is followed by structured reassessment and postoperative planning.','بعد السيطرة على النزف يجب إعادة تقييم الحالة الدموية والنزف والإرقاء ووضع خطة ما بعد الجراحة.','reassessment'],
      ['Debrief','The patient is transferred for continued monitoring.','نُقلت المريضة للمراقبة المستمرة.','What is the key OR lesson?','ما الدرس الأساسي في غرفة العمليات؟',['Think ahead: team, blood, resuscitation, diagnosis, safe surgical strategy and continuous reassessment','Focus only on the operation itself','Wait for deterioration before calling for help','Treat laboratory values without the patient context'],0,'Major obstetric surgery requires anticipation, teamwork, resuscitation and repeated reassessment.','الجراحة التوليدية الكبرى تحتاج الاستباق والعمل الجماعي والإنعاش وإعادة التقييم المستمرة.','debrief']
    ]
  }
];

const T={en:{subtitle:'Clinical Decision Challenge',eyebrow:'EMERGENCY DEPARTMENT • NIGHT SHIFT',heroTitle:'Can you <span>save</span> the patient?',heroText:'Choose a case, investigate, prioritize and make decisions under pressure. Every choice changes the case.',missionTitle:'🎯 Your mission',mission:'Think first — assess, ask, examine, investigate, act and reassess.',start:'START CHALLENGE →',levelsTitle:'Emergency Levels',levelsText:'Every level contains 10 linked clinical decisions.',back:'← Home',choose:'Choose your case',score:'Score',patient:'Patient',status:'Patient status',stability:'Stability',progress:'Case progress',exit:'↩ Exit level',continue:'CONTINUE →',complete:'LEVEL COMPLETE',outcome:'🏆 Patient outcome',correct:'Best decisions',errors:'Critical errors',health:'Patient health',play:'PLAY AGAIN ↻',another:'CHOOSE ANOTHER LEVEL',role:'OB/GYN Resident • Medical Educator',credits:'Created and designed for medical education and clinical decision-making practice.',level:'LEVEL',tools:'Clinical tools',why:'WHY?',consequence:'Clinical consequence',used:'Used',ask:'Ask / review',vitals:'Vitals',exam:'Examination',labs:'Investigations',team:'Team',reassess:'Reassess',history:'History',locked:'Complete the previous level',finish:'FINISH CASE'},ar:{subtitle:'تحدي اتخاذ القرار السريري',eyebrow:'قسم الإسعاف • المناوبة الليلية',heroTitle:'هل تستطيع <span>إنقاذ</span> المريضة؟',heroText:'اختر حالة، اجمع المعلومات، رتب الأولويات واتخذ القرارات تحت الضغط. كل قرار يغيّر مسار الحالة.',missionTitle:'🎯 مهمتك',mission:'فكّر أولًا — قيّم، اسأل، افحص، اطلب الفحوص، تدخل ثم أعد التقييم.',start:'ابدأ التحدي ←',levelsTitle:'مستويات الطوارئ',levelsText:'كل مستوى يحتوي على 10 قرارات سريرية مترابطة.',back:'العودة ←',choose:'اختر الحالة',score:'النقاط',patient:'المريضة',status:'حالة المريضة',stability:'الاستقرار',progress:'تقدم الحالة',exit:'↩ خروج من المستوى',continue:'متابعة ←',complete:'اكتمل المستوى',outcome:'🏆 نتيجة المريضة',correct:'القرارات الأفضل',errors:'الأخطاء الحرجة',health:'صحة المريضة',play:'إعادة اللعب ↻',another:'اختيار مستوى آخر',role:'مقيم نسائية وتوليد • مثقف طبي',credits:'صُممت للتعليم الطبي والتدرب على اتخاذ القرار السريري.',level:'المستوى',tools:'أدوات التفكير السريري',why:'لماذا؟',consequence:'النتيجة السريرية',used:'مستخدمة',ask:'اسأل / راجع',vitals:'العلامات الحيوية',exam:'الفحص السريري',labs:'الاستقصاءات',team:'الفريق',reassess:'إعادة التقييم',history:'القصة المرضية',locked:'أكمل المستوى السابق',finish:'إنهاء الحالة'}};

let lang='en', current=null, stepIndex=0, score=0, health=100, errors=0, best=0, toolUses=0;
const $=id=>document.getElementById(id);
const t=()=>T[lang];
const escapeHtml=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

function setText(id,val){const e=$(id);if(e)e.innerHTML=val;}
function setLanguage(){
 document.documentElement.lang=lang;document.body.dir=lang==='ar'?'rtl':'ltr';
 ['subtitle','eyebrow','heroText','missionTitle','mission','startBtn','levelsTitle','levelsText','backHome','scoreLabel','patientLabel','statusTitle','stabilityLabel','timelineTitle','quitBtn','complete','outcome','correctLabel','errorsLabel','healthLabel','replayBtn','levelsBtn','creditsRole','creditsText'].forEach(()=>{});
 if($('subtitle'))$('subtitle').textContent=t().subtitle;if($('eyebrow'))$('eyebrow').textContent=t().eyebrow;if($('heroText'))$('heroText').textContent=t().heroText;if($('missionTitle'))$('missionTitle').textContent=t().missionTitle;if($('mission'))$('mission').textContent=t().mission;if($('startBtn'))$('startBtn').textContent=t().start;if($('levelsTitle'))$('levelsTitle').textContent=t().levelsTitle;if($('levelsText'))$('levelsText').textContent=t().levelsText;if($('backHome'))$('backHome').textContent=t().back;if($('scoreLabel'))$('scoreLabel').textContent=t().score;if($('patientLabel'))$('patientLabel').textContent=t().patient;if($('statusTitle'))$('statusTitle').textContent=t().status;if($('stabilityLabel'))$('stabilityLabel').textContent=t().stability;if($('timelineTitle'))$('timelineTitle').textContent=t().progress;if($('quitBtn'))$('quitBtn').textContent=t().exit;if($('complete'))$('complete').textContent=t().complete;if($('outcome'))$('outcome').textContent=t().outcome;if($('correctLabel'))$('correctLabel').textContent=t().correct;if($('errorsLabel'))$('errorsLabel').textContent=t().errors;if($('healthLabel'))$('healthLabel').textContent=t().health;if($('replayBtn'))$('replayBtn').textContent=t().play;if($('levelsBtn'))$('levelsBtn').textContent=t().another;if($('creditsRole'))$('creditsRole').textContent=t().role;if($('creditsText'))$('creditsText').textContent=t().credits;
 renderLevels(); if(current) renderStep();
}

function unlocks(){return Number(localStorage.getItem('obgynUnlocked')||1);}
function renderLevels(){
 const grid=$('levelGrid');if(!grid)return;const u=unlocks();
 grid.innerHTML=LEVELS.map((c,i)=>{const unlocked=i<u;return `<button class="levelCard ${unlocked?'':'locked'}" data-level="${i}" ${unlocked?'':'disabled'}><div class="levelIcon">${c.emoji}</div><div><small>${t().level} ${i+1}</small><h3>${escapeHtml(c[lang])}</h3><p>${escapeHtml(lang==='ar'?c.detailsAr:c.detailsEn)}</p><strong>${unlocked?'10 '+(lang==='ar'?'قرارات':'decisions'):'🔒 '+t().locked}</strong></div></button>`;}).join('');
 grid.querySelectorAll('[data-level]').forEach(b=>b.addEventListener('click',()=>startLevel(Number(b.dataset.level))));
}
function show(id){['home','levels','game','end'].forEach(x=>$(x)?.classList.toggle('hidden',x!==id));window.scrollTo({top:0,behavior:'smooth'});}
function startLevel(i){current=LEVELS[i];stepIndex=0;score=0;health=100;errors=0;best=0;toolUses=0;$('score').textContent='0';$('health').textContent='100';show('game');renderStep();}
function toolPanel(){
 const s=current.steps[stepIndex];
 const toolMap={assessment:['🩺',t().vitals,'Current observations: BP/HR/SpO₂ and overall appearance.'],history:['🗣️',t().history,'Ask what matters to the current emergency: bleeding, pain, symptoms of collapse, previous surgery and relevant risk factors.'],examination:['🔎',t().exam,'Focus your examination on the immediate problem and signs of deterioration.'],investigation:['🔬',t().labs,'Choose investigations that can change immediate management; avoid delaying time-critical treatment.'],resuscitation:['🩸',t().vitals,'Reassess haemodynamics and prepare appropriate access, monitoring and blood support when indicated.'],team:['👥',t().team,'Call the appropriate senior, anaesthetic, theatre, neonatal or transfusion support for the situation.'],reassessment:['📈',t().reassess,'Compare the new clinical state with the previous one before deciding again.'],deterioration:['🚨',t().vitals,'The patient is deteriorating. Re-prioritize ABCs, escalation and definitive control.'],surgical:['🔪','Surgical planning','Base the decision on diagnosis, haemodynamic status, extent of disease, expertise and local protocol.'],decision:['🎯','Decision support','Ask: what is the immediate threat, what can safely wait, and what action changes the outcome now?'],debrief:['📚','Debrief','Review the principle behind the decision and how the patient trajectory changed.']};
 const item=toolMap[s[8]]||toolMap.assessment;
 return `<div class="clinicalTools"><div class="toolsTitle">🧰 ${t().tools}</div><div class="toolGrid"><button class="toolBtn" data-tool="${s[8]}">${item[0]} ${item[1]}</button><button class="toolBtn" data-tool="decision">🎯 ${t().ask}</button><button class="toolBtn" data-tool="reassess">📈 ${t().reassess}</button></div><div id="toolResult" class="toolResult hidden"></div></div>`;
}
function renderStep(){
 const s=current.steps[stepIndex];
 $('caseTag').textContent=`${t().level} ${LEVELS.indexOf(current)+1} • ${stepIndex+1}/10`;$('caseTitle').textContent=current[lang];$('caseBrief').textContent=lang==='ar'?s[2]:s[1];$('visualLabel').textContent=lang==='ar'?'المشهد السريري':'Clinical scene';$('visualArt').innerHTML=`<div class="sceneCard"><span>${current.emoji}</span><b>${escapeHtml(lang==='ar'?s[0]:s[0])}</b><small>${stepIndex+1} / 10</small></div>`;
 $('progress').textContent=`${stepIndex+1}/10`;$('avatar').textContent=current.emoji;$('patientName').textContent=current.patient;$('patientDetails').textContent=lang==='ar'?current.detailsAr:current.detailsEn;$('stability').textContent=health>70?(lang==='ar'?'مستقرة نسبيًا':'Relatively stable'):health>40?(lang==='ar'?'مقلقة':'Concerning'):(lang==='ar'?'غير مستقرة':'Unstable');$('health').textContent=health;$('healthBar').style.width=health+'%';
 const choices=s[5].map((text,i)=>({text,i}));
 for(let i=choices.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[choices[i],choices[j]]=[choices[j],choices[i]];}
 $('choices').innerHTML=`<div class="questionPrompt">${escapeHtml(lang==='ar'?s[3]:s[3])}</div>${choices.map((c,i)=>`<button class="choice" data-original="${c.i}"><span>${String.fromCharCode(65+i)}</span>${escapeHtml(c.text)}</button>`).join('')}`+toolPanel();
 $('feedback').classList.add('hidden');$('nextBtn').classList.add('hidden');$('nextBtn').textContent=stepIndex===9?t().finish:t().continue;
 $('choices').querySelectorAll('.choice').forEach(b=>b.addEventListener('click',()=>choose(Number(b.dataset.original),b)));
 document.querySelectorAll('.toolBtn').forEach(b=>b.addEventListener('click',()=>useTool(b.dataset.tool)));
 renderTimeline();
}
function useTool(type){toolUses++;const box=$('toolResult');if(!box)return;const s=current.steps[stepIndex];let title,body;
 if(type==='reassess'){title=lang==='ar'?'إعادة التقييم':'Reassessment';body=health>70?(lang==='ar'?'لا توجد علامة على انهيار فوري؛ تابع التقييم حسب السياق.':'No immediate sign of collapse; continue assessment in context.'):(lang==='ar'?'المريضة تتدهور؛ أعد ترتيب الأولويات وصعّد التدبير.':'The patient is deteriorating; reprioritize and escalate.');}
 else if(type==='decision'){title=lang==='ar'?'مساعد التفكير':'Thinking prompt';body=lang==='ar'?'اسأل نفسك: ما الخطر الذي يهدد الحياة الآن؟ ما المعلومة التي ستغير قراري؟ هل هناك إجراء لا يحتمل التأخير؟':'Ask yourself: What is the immediate threat? Which information would change my decision? Is there an action that cannot safely wait?';}
 else {const map={assessment:['Assessment','ابدأ بتقييم ABC والاستقرار الديناميكي الدموي قبل الغرق في التفاصيل.'],history:['History','اسأل فقط ما يغير قرارك الفوري أو يكشف عامل خطر مهم.'],examination:['Examination','افحص ما يجيب عن المشكلة الحالية ويكشف التدهور.'],investigation:['Investigation','اطلب الفحص الذي سيغير التدبير؛ لا تجعل الاستقصاء سببًا لتأخير العلاج المنقذ للحياة.'],resuscitation:['Resuscitation','الإنعاش والتدبير السببي يمكن أن يسيرا بالتوازي في الحالات الحساسة للوقت.'],team:['Team','استدعِ الفريق المناسب مبكرًا عندما تتجاوز الحالة قدرة شخص واحد.'],surgical:['Surgical planning','فكر بالتشخيص، الاستقرار، شدة النزف، الموارد، الخبرة والبروتوكول المحلي.'],deterioration:['Deterioration','عند التدهور ارجع إلى ABC، صعّد المساعدة وابدأ السيطرة النهائية على السبب.'],debrief:['Debrief','الفكرة الأساسية هي ربط القرار بالمشكلة التي تحاول تغييرها.']};const x=map[type]||map.assessment;title=lang==='ar'?x[0]:x[0];body=lang==='ar'?x[1]:x[0]==='Team'?'Call the appropriate team early when the case exceeds one clinician’s capacity.':x[0]==='Investigation'?'Choose tests that change management; do not let testing delay life-saving treatment.':'Use the tool to focus your next clinical priority.';}
 box.innerHTML=`<b>${escapeHtml(title)}</b><p>${escapeHtml(body)}</p><small>${t().used}: ${toolUses}</small>`;box.classList.remove('hidden');
}
function choose(original,button){
 const s=current.steps[stepIndex];const correct=original===s[6];$('choices').querySelectorAll('.choice').forEach(b=>b.disabled=true);button.classList.add(correct?'correct':'wrong');
 if(correct){score+=10;best++;$('score').textContent=score;}
 else {score=Math.max(0,score-5);health=Math.max(0,health-12);errors++;$('score').textContent=score;$('health').textContent=health;}
 const consequence=correct?(lang==='ar'?'قرار مناسب — تنتقل الحالة إلى المرحلة التالية مع الحفاظ على استقرار المريضة.':'Appropriate decision — the case progresses with the patient trajectory preserved.'):(lang==='ar'?'قد يؤدي هذا القرار إلى تأخير أو ضرر؛ راجع الأولوية قبل المتابعة.':'This decision may cause delay or harm; review the priority before continuing.');
 const why=lang==='ar'?s[7]:s[7-0];
 $('feedback').innerHTML=`<div class="feedbackHead">${correct?'✅':'⚠️'} ${correct?(lang==='ar'?'قرار جيد':'Good decision'):(lang==='ar'?'قرار يحتاج مراجعة':'Review this decision')}</div><div><b>${t().why}</b><p>${escapeHtml(why)}</p></div><div><b>${t().consequence}</b><p>${escapeHtml(consequence)}</p></div>`;$('feedback').classList.remove('hidden');$('nextBtn').classList.remove('hidden');$('health').textContent=health;$('healthBar').style.width=health+'%';renderTimeline();
}
function renderTimeline(){$('timeline').innerHTML=current.steps.map((s,i)=>`<span class="tlDot ${i<stepIndex?'done':i===stepIndex?'active':''}">${i+1}</span>`).join('');}
function finish(){
 const max=current.steps.length*10;const pct=Math.round(score/max*100);$('finalScore').textContent=score;$('correctCount').textContent=`${best}/10`;$('errorCount').textContent=errors;$('finalHealth').textContent=health+'%';$('rank').textContent=pct>=90?'🏆 Excellent clinical reasoning':pct>=75?'⭐ Strong performance':'📚 Keep practicing';$('endMessage').textContent=lang==='ar'?`أكملت ${current.ar}. النتيجة ${pct}%. راجع القرارات التي سببت تدهورًا وحاول مرة أخرى.`:`You completed ${current.en}. Performance ${pct}%. Review decisions that caused deterioration and try again.`;
 const idx=LEVELS.indexOf(current);if(pct>=70&&idx+1>unlocks())localStorage.setItem('obgynUnlocked',String(Math.min(LEVELS.length,idx+2)));show('end');
}
function init(){
 $('langBtn')?.addEventListener('click',()=>{lang=lang==='en'?'ar':'en';$('langBtn').textContent=lang==='en'?'عربي 🇸🇾':'English 🇬🇧';setLanguage();});$('startBtn')?.addEventListener('click',()=>show('levels'));$('backHome')?.addEventListener('click',()=>show('home'));$('levelsBtn')?.addEventListener('click',()=>{renderLevels();show('levels');});$('replayBtn')?.addEventListener('click',()=>startLevel(LEVELS.indexOf(current)));$('quitBtn')?.addEventListener('click',()=>{current=null;show('levels');});$('nextBtn')?.addEventListener('click',()=>{if(stepIndex<9){stepIndex++;renderStep();}else finish();});setLanguage();
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
