const CASES={
  ectopic:{emoji:'🚨',patient:'Sara',details:'28 years • 7 weeks pregnant',en:'Ruptured Ectopic Pregnancy',ar:'الحمل الهاجر المتمزق',steps:[
    ['Arrival','A 28-year-old pregnant patient arrives with severe unilateral lower abdominal pain, vaginal bleeding and dizziness.','ما الإجراء الأول؟',['Assess ABCs, begin resuscitation and call for help','Wait for serial β-hCG','Give methotrexate immediately','Discharge her'],0,'An unstable patient needs immediate stabilization; do not delay life-saving care.','المريضة غير المستقرة تحتاج إلى التقييم والتثبيت الفوريين؛ لا تؤخر التدبير المنقذ للحياة.'],
    ['Clues','BP 82/50, HR 128. She is pale and dizzy.','ماذا تعني العلامات الحيوية؟',['Hemodynamic instability','Normal early pregnancy','Stable because SpO₂ is normal','No action is needed'],0,'Hypotension with tachycardia indicates hemodynamic instability.','انخفاض الضغط مع تسرع القلب يدل على عدم الاستقرار الديناميكي الدموي.'],
    ['Ultrasound','Pregnancy test is positive; no intrauterine pregnancy is seen and free fluid is present.','ما التشخيص الأكثر احتمالًا؟',['Ruptured ectopic pregnancy','Placenta previa','Hyperemesis','Normal pregnancy'],0,'This combination in an unstable patient is highly concerning for ruptured ectopic pregnancy.','هذه المعطيات لدى مريضة غير مستقرة تثير الشك بقوة بحمل هاجر متمزق.'],
    ['Act now','She remains unstable and the emergency surgical team is ready.','ما التوجه النهائي؟',['Urgent operative management while resuscitation continues','Wait for serial β-hCG','Methotrexate and observation','Outpatient follow-up'],0,'Suspected rupture with hemodynamic instability requires urgent surgical management while resuscitation continues.','الاشتباه بالتمزق مع عدم الاستقرار يتطلب تدبيرًا جراحيًا إسعافيًا مع استمرار الإنعاش.']
  ]},
  normalbirth:{emoji:'👶',patient:'Maya',details:'25 years • 39+2 weeks • active labor',en:'Normal Vaginal Birth',ar:'الولادة المهبلية الطبيعية',steps:[
    ['Arrival','A healthy term patient is in active labor. FHR is reassuring and maternal observations are stable.','ما الخطوة المناسبة؟',['Support labor and continue maternal/fetal assessment','Immediate cesarean section','Stop all monitoring','Give magnesium sulfate'],0,'Reassuring term labor is managed with supportive care and ongoing assessment.','في المخاض الطبيعي مع حالة مطمئنة، نستمر بالدعم والمراقبة والتقييم المستمر.'],
    ['Second stage','The fetal head is crowning and the mother is pushing effectively.','ما الأولوية؟',['Support controlled birth and monitor maternal/fetal status','Routine fundal pressure','Pull strongly on the head','Leave the room'],0,'Support the mother and allow controlled delivery while monitoring mother and fetus.','ادعم الأم واسمح بولادة مضبوطة مع مراقبة حالة الأم والجنين.'],
    ['After birth','The baby is born breathing and crying.','ماذا تفعل بعد الولادة؟',['Assess the newborn, support skin-to-skin and monitor the mother','Ignore uterine tone','Separate mother and baby without indication','Give oxytocin only if severe bleeding develops'],0,'Routine postpartum care includes newborn assessment, maternal observation and prevention of postpartum haemorrhage according to local protocol.','تشمل الرعاية تقييم الوليد ومراقبة الأم والوقاية من نزف ما بعد الولادة وفق البروتوكول المحلي.'],
    ['Third stage','The placenta is delivered; the uterus is firm and blood loss is minimal.','ما أفضل متابعة؟',['Continue postpartum observation and assess bleeding and uterine tone','Discharge immediately','Stop all observations','Order CT'],0,'Continue routine postpartum observation and reassess bleeding and uterine tone.','استمر بالمراقبة بعد الولادة وأعد تقييم النزف وتوتر الرحم.']
  ]},
  preeclampsia:{emoji:'⚡',patient:'Lina',details:'31 years • 35 weeks • severe headache',en:'Preeclampsia / Eclampsia',ar:'مقدمات الارتعاج / الإرجاج',steps:[
    ['Red flag','BP 170/112 with severe headache and visual symptoms at 35 weeks.','ما الأولوية؟',['Recognize severe hypertension and urgently assess and stabilize','Send her home to rest','Wait until tomorrow','Give only oral fluids'],0,'Severe-range hypertension with neurologic symptoms is a maternal emergency requiring urgent assessment, stabilization and treatment.','ارتفاع الضغط ضمن المجال الشديد مع أعراض عصبية حالة إسعافية تتطلب التقييم والتثبيت والعلاج العاجلين.'],
    ['Prevent seizure','She is at high risk of eclampsia.','ما الدواء المستخدم للوقاية من الاختلاجات؟',['Magnesium sulfate','Methotrexate','Oxytocin','Warfarin'],0,'Magnesium sulfate is used for seizure prophylaxis in severe preeclampsia and for treatment of eclampsia according to protocol; it does not replace urgent BP control.','يُستخدم مغنزيوم سلفات للوقاية من الاختلاجات في مقدمات الارتعاج الشديدة ولعلاج الإرجاج وفق البروتوكول، ولا يحل محل خفض الضغط العاجل.'],
    ['Seizure','The patient suddenly develops a generalized seizure.','ماذا تفعل أولًا؟',['Protect safety and airway, call for help and give magnesium sulfate according to protocol','Restrain her forcefully','Put an object in her mouth','Leave her alone'],0,'During eclampsia, protect the patient, support ABCs, call for help and administer magnesium sulfate according to protocol.','أثناء الإرجاج أمّن سلامة المريضة والطريق الهوائي وادعم ABC واستدعِ المساعدة وأعطِ مغنزيوم سلفات وفق البروتوكول.'],
    ['Definitive plan','After stabilization, the team reviews maternal and fetal status.','ما المبدأ الصحيح؟',['Stabilize the mother first, then plan delivery based on the clinical situation','Delay all action for weeks','Discharge after the seizure','Treat only the headache'],0,'Maternal stabilization comes first; delivery planning follows the clinical picture and gestational context.','تثبيت الأم يأتي أولًا؛ ثم يُخطط للولادة بحسب الحالة السريرية وعمر الحمل.']
  ]},
  pph:{emoji:'🩸',patient:'Nour',details:'29 years • 20 min after vaginal birth',en:'Postpartum Hemorrhage',ar:'نزف ما بعد الولادة',steps:[
    ['Alarm','Heavy vaginal bleeding begins 20 minutes after birth. The patient is pale and tachycardic.','ما الأولوية؟',['Call for help, assess ABCs, quantify blood loss and start resuscitation','Wait 30 minutes','Discharge her','Give analgesia only'],0,'PPH is time-critical: escalate, resuscitate, quantify blood loss and identify the cause.','نزف ما بعد الولادة حالة حساسة للوقت: صعّد التدبير، ابدأ الإنعاش، قِس كمية الدم وحدد السبب.'],
    ['Tone','The uterus feels boggy and enlarged.','ما السبب الأكثر احتمالًا؟',['Uterine atony','Ectopic pregnancy','Placenta previa before birth','Hyperemesis'],0,'A boggy uterus after birth strongly suggests uterine atony.','الرحم الرخو والمتضخم بعد الولادة يشير بقوة إلى وهن الرحم.'],
    ['First-line action','Atony is suspected and bleeding continues.','ما التدبير المناسب؟',['Uterine massage plus uterotonic treatment according to protocol while resuscitation continues','Wait for ultrasound before acting','Ignore the bleeding','Give methotrexate'],0,'Immediate uterine massage and uterotonic therapy are key components while resuscitation continues.','تدليك الرحم وإعطاء القابضات الرحمية وفق البروتوكول من التدابير الأساسية مع استمرار الإنعاش.'],
    ['TXA','PPH is diagnosed and bleeding continues.','ما الإضافة العلاجية المهمة؟',['Give IV tranexamic acid early, as soon as possible and within 3 hours of birth, according to protocol','Give methotrexate','Delay treatment until tomorrow','Stop resuscitation'],0,'WHO recommends early IV tranexamic acid for clinically diagnosed PPH, as soon as possible and within 3 hours of birth, in addition to standard care.','توصي منظمة الصحة العالمية بإعطاء حمض الترانيكساميك وريديًا مبكرًا عند تشخيص نزف ما بعد الولادة، بأسرع ما يمكن وخلال 3 ساعات من الولادة، إضافة إلى الرعاية القياسية.'],
    ['Escalate','Bleeding remains heavy despite initial measures.','ماذا تفعل؟',['Activate the hemorrhage response and rapidly escalate to definitive bleeding control and blood products as indicated','Send her home','Stop monitoring','Wait several hours'],0,'Persistent hemorrhage requires rapid escalation, ongoing resuscitation and definitive control of bleeding.','النزف المستمر يحتاج تصعيدًا سريعًا، واستمرار الإنعاش والسيطرة النهائية على النزف.']
  ]},
  shoulder:{emoji:'🧑‍🍼',patient:'Hala',details:'30 years • term • head delivered',en:'Shoulder Dystocia',ar:'عسر ولادة الكتف',steps:[
    ['Recognition','The head delivers but retracts against the perineum and the shoulders do not deliver with gentle traction.','ما التشخيص؟',['Shoulder dystocia','Normal delivery','Placental abruption','Eclampsia'],0,'Failure of the shoulders to deliver after the head despite gentle traction is consistent with shoulder dystocia.','عدم ولادة الكتفين بعد الرأس رغم الشد اللطيف يتوافق مع عسر ولادة الكتف.'],
    ['Call','Shoulder dystocia is recognized.','ما أول خطوة تنظيمية؟',['Call for help, announce the emergency and stop excessive traction','Pull harder on the head','Leave the patient','Wait'],0,'Call for help, communicate clearly and avoid excessive traction on the fetal head.','استدعِ المساعدة وأعلن الحالة وتجنب الشد المفرط على رأس الجنين.'],
    ['Maneuver','The team begins first-line maneuvers.','ما المناورة المناسبة؟',['McRoberts maneuver with suprapubic pressure as appropriate','Fundal pressure','Forceful downward traction','Routine episiotomy alone'],0,'McRoberts is a key first-line maneuver; suprapubic pressure can be added. Fundal pressure should not be used.','ماكروبرتس من المناورات الأساسية الأولى، ويمكن إضافة الضغط فوق العانة. ويجب عدم استخدام الضغط على قاع الرحم.'],
    ['After birth','The baby is delivered and the team reassesses both patients.','ما الخطوة المهمة؟',['Assess newborn and mother for complications and document the emergency','End all monitoring immediately','Ignore maternal bleeding','Assume no injury'],0,'After shoulder dystocia, assess for neonatal and maternal complications and document the event.','بعد عسر ولادة الكتف يجب تقييم مضاعفات الأم والوليد وتوثيق الحدث.']
  ]}
};

const T={en:{subtitle:'Clinical Decision Challenge',eyebrow:'EMERGENCY DEPARTMENT • NIGHT SHIFT',heroTitle:'Can you <span>save</span> the patient?',heroText:'Choose a clinical scenario, assess the patient, recognize the emergency and make the right decision under pressure.',missionTitle:'🎯 Your mission',mission:'Learn by doing — every choice changes the patient outcome.',start:'START CHALLENGE →',levelsTitle:'Emergency Levels',levelsText:'Choose a scenario. Harder cases unlock as you complete levels.',back:'← Home',choose:'Choose your case',score:'Score',patient:'Patient',status:'Patient status',stability:'Stability',progress:'Case progress',exit:'↩ Exit level',continue:'CONTINUE →',complete:'LEVEL COMPLETE',outcome:'🏆 Patient outcome',correct:'Correct decisions',errors:'Critical errors',health:'Patient health',play:'PLAY AGAIN ↻',another:'CHOOSE ANOTHER LEVEL',role:'OB/GYN Resident • Medical Educator',credits:'Created and designed for medical education and clinical decision-making practice.',excellent:'🔥 Excellent clinical prioritization!',good:'👏 Good work. Review the missed decisions and try again.',needs:'Keep practicing — prioritize ABCs, recognition and escalation.',locked:'Complete the previous level',level:'LEVEL',home:'Home'},ar:{subtitle:'تحدي اتخاذ القرار السريري',eyebrow:'قسم الإسعاف • المناوبة الليلية',heroTitle:'هل تستطيع <span>إنقاذ</span> المريضة؟',heroText:'اختر سيناريو سريريًا، قيّم المريضة، تعرّف على الطوارئ واتخذ القرار الصحيح تحت الضغط.',missionTitle:'🎯 مهمتك',mission:'تعلّم بالممارسة — كل قرار يؤثر في نتيجة المريضة.',start:'ابدأ التحدي ←',levelsTitle:'مستويات الطوارئ',levelsText:'اختر سيناريو. ستُفتح الحالات الأصعب مع تقدمك.',back:'العودة ←',choose:'اختر الحالة',score:'النقاط',patient:'المريضة',status:'حالة المريضة',stability:'الاستقرار',progress:'تقدم الحالة',exit:'↩ خروج من المستوى',continue:'متابعة ←',complete:'اكتمل المستوى',outcome:'🏆 نتيجة المريضة',correct:'القرارات الصحيحة',errors:'الأخطاء الحرجة',health:'حالة المريضة',play:'إعادة اللعب ↻',another:'اختيار مستوى آخر',role:'طبيب مقيم في النسائية والتوليد • مهتم بالتعليم الطبي',credits:'تم إنشاء وتصميم اللعبة للتعليم الطبي والتدرب على اتخاذ القرار السريري.',excellent:'🔥 ممتاز! ترتيب أولويات سريري رائع.',good:'👏 عمل جيد. راجع القرارات التي أخطأت بها وحاول مجددًا.',needs:'استمر بالتدرب — ركز على ABC والتعرف على الطوارئ والتصعيد.',locked:'أكمل المستوى السابق أولًا',level:'المستوى',home:'الرئيسية'}};

let lang=localStorage.getItem('obgynLang')||'en',levelId=null,step=0,score=0,health=100,errors=0,correct=0,answered=false;
const $=id=>document.getElementById(id);
const ids=Object.keys(CASES);
const unlocked=()=>Math.min(ids.length,Math.max(1,Number(localStorage.getItem('obgynUnlocked')||1)));
const arDetails={ectopic:'٢٨ سنة • حمل ٧ أسابيع',normalbirth:'٢٥ سنة • ٣٩+٢ أسبوع • مخاض فعال',preeclampsia:'٣١ سنة • ٣٥ أسبوعًا • صداع شديد وأعراض بصرية',pph:'٢٩ سنة • بعد ٢٠ دقيقة من الولادة المهبلية',shoulder:'٣٠ سنة • حمل تام • وُلد الرأس ولم تلد الكتفين'};
const stepLabels={Arrival:['What is the first action?','ما الإجراء الأول؟'],Clues:['What do the vital signs indicate?','ماذا تعني العلامات الحيوية؟'],Ultrasound:['What is the most likely diagnosis?','ما التشخيص الأكثر احتمالًا؟'],['Act now']:['What is the definitive approach?','ما التوجه النهائي؟'],['Second stage']:['What is the priority?','ما الأولوية؟'],['After birth']:['What should you do after birth?','ماذا تفعل بعد الولادة؟'],['Third stage']:['What is the best follow-up?','ما أفضل متابعة؟'],['Red flag']:['What is the priority?','ما الأولوية؟'],['Prevent seizure']:['Which medication is used for seizure prophylaxis?','ما الدواء المستخدم للوقاية من الاختلاجات؟'],Seizure:['What should you do first?','ماذا تفعل أولًا؟'],['Definitive plan']:['What is the correct principle?','ما المبدأ الصحيح؟'],Alarm:['What is the priority?','ما الأولوية؟'],Tone:['What is the most likely cause?','ما السبب الأكثر احتمالًا؟'],['First-line action']:['What is the appropriate action?','ما التدبير المناسب؟'],TXA:['What important adjunct should be considered?','ما الإضافة العلاجية المهمة؟'],Escalate:['What should you do?','ماذا تفعل؟'],Recognition:['What is the diagnosis?','ما التشخيص؟'],Call:['What is the first organizational step?','ما أول خطوة تنظيمية؟'],Maneuver:['Which maneuver is appropriate?','ما المناورة المناسبة؟']};
function scene(c,s){const icons=['🩺','❤️','🧪','🚨','👶'];return `<div class="sceneIcon">${c.emoji}</div><div class="scenePulse">${icons[s%icons.length]}</div><div class="sceneText">${lang==='ar'?'مراقبة سريرية نشطة':'ACTIVE CLINICAL MONITOR'}</div>`}
function applyText(){const t=T[lang]; document.documentElement.lang=lang;document.body.dir=lang==='ar'?'rtl':'ltr';$('subtitle').textContent=t.subtitle;$('eyebrow').textContent=t.eyebrow;$('heroTitle').innerHTML=t.heroTitle;$('heroText').textContent=t.heroText;$('missionTitle').textContent=t.missionTitle;$('mission').textContent=t.mission;$('startBtn').textContent=t.start;$('levelsTitle').textContent=t.levelsTitle;$('levelsText').textContent=t.levelsText;$('backHome').textContent=t.back;$('scoreLabel').textContent=t.score;$('patientLabel').textContent=t.patient;$('statusTitle').textContent=t.status;$('stabilityLabel').textContent=t.stability;$('timelineTitle').textContent=t.progress;$('quitBtn').textContent=t.exit;$('complete').textContent=t.complete;$('outcome').textContent=t.outcome;$('correctLabel').textContent=t.correct;$('errorsLabel').textContent=t.errors;$('healthLabel').textContent=t.health;$('replayBtn').textContent=t.play;$('levelsBtn').textContent=t.another;$('creditsRole').textContent=t.role;$('creditsText').textContent=t.credits;$('langBtn').textContent=lang==='ar'?'English 🇬🇧':'عربي 🇸🇾';$('musicBtn').style.display='none';$('disclaimer').textContent=lang==='ar'?'محاكاة تعليمية فقط. اتبع البروتوكولات المحلية والإرشادات السريرية المعتمدة عند التعامل مع المرضى الحقيقيين.':'Educational simulation only. Follow local protocols and approved clinical guidance when caring for real patients.';renderLevels();if(levelId)renderStep()}
function renderLevels(){const max=unlocked();$('levelGrid').innerHTML=ids.map((id,i)=>{const c=CASES[id],lock=i+1>max;return `<button class="levelCard ${lock?'locked':''}" data-id="${id}" ${lock?'disabled':''}><div class="levelNo">${T[lang].level} ${i+1}</div><div class="levelEmoji">${c.emoji}</div><h3>${lang==='ar'?c.ar:c.en}</h3><p>${lang==='ar'?arDetails[id]:c.details}</p><span>${lock?'🔒 '+T[lang].locked:'▶ '+T[lang].choose}</span></button>`}).join('');document.querySelectorAll('.levelCard:not(.locked)').forEach(b=>b.onclick=()=>startLevel(b.dataset.id))}
function renderStep(){const c=CASES[levelId],s=c.steps[step];$('caseTag').textContent=`${T[lang].level} ${ids.indexOf(levelId)+1}`;$('caseTitle').textContent=lang==='ar'?c.ar:c.en;$('progress').textContent=`${step+1} / ${c.steps.length}`;$('caseBrief').textContent=lang==='ar'?s[6]:s[1];$('visualLabel').textContent=lang==='ar'?'المشهد السريري':'CLINICAL SCENE';$('visualArt').innerHTML=scene(c,step);$('patientName').textContent=c.patient;$('patientDetails').textContent=lang==='ar'?arDetails[levelId]:c.details;updateHealth();const q=stepLabels[s[0]]?.[lang==='ar'?1:0]||s[2];$('choices').innerHTML=`<h3 class="question">${q}</h3>`+s[3].map((x,i)=>`<button class="choice" data-i="${i}"><span class="letter">${String.fromCharCode(65+i)}</span><span>${lang==='ar'?translateChoice(levelId,step,i):x}</span></button>`).join('');$('feedback').className='feedback hidden';$('nextBtn').classList.add('hidden');answered=false;document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>answer(+b.dataset.i));renderTimeline()}
function translateChoice(id,st,i){const s=CASES[id].steps[st];const ar=s[6];const maps={ectopic:[['ابدأ بتقييم ABC والإنعاش واستدعاء المساعدة','انتظر β-hCG المتسلسل','أعطِ ميثوتركسات فورًا','أخرج المريضة'],['عدم الاستقرار الديناميكي الدموي','حمل مبكر طبيعي','مستقرة لأن تشبع الأكسجين طبيعي','لا حاجة لأي إجراء'],['حمل هاجر متمزق','مشيمة منزاحة','فرط إقياء','حمل طبيعي'],['تدبير جراحي إسعافي مع استمرار الإنعاش','انتظر β-hCG المتسلسل','ميثوتركسات ومراقبة','متابعة خارجية']],normalbirth:[['دعم المخاض والاستمرار بتقييم الأم والجنين','قيصرية فورية','إيقاف كل المراقبة','إعطاء مغنزيوم سلفات'],['دعم الولادة المضبوطة ومراقبة الأم والجنين','ضغط روتيني على قاع الرحم','الشد بقوة على الرأس','مغادرة الغرفة'],['تقييم الوليد ودعم التلامس جلدًا لجلد ومراقبة الأم','تجاهل توتر الرحم','فصل الأم والوليد دون داعٍ','إعطاء أوكسيتوسين فقط عند حدوث نزف شديد'],['استمرار المراقبة بعد الولادة وتقييم النزف وتوتر الرحم','إخراج المريضة فورًا','إيقاف كل المراقبة','طلب CT']],preeclampsia:[['التعرف على ارتفاع الضغط الشديد والتقييم والتثبيت العاجلين','إرسالها للمنزل','الانتظار حتى الغد','إعطاء سوائل فموية فقط'],['مغنزيوم سلفات','ميثوتركسات','أوكسيتوسين','وارفارين'],['تأمين السلامة والطريق الهوائي ودعم ABC واستدعاء المساعدة وإعطاء مغنزيوم سلفات وفق البروتوكول','تقييدها بقوة','وضع شيء في فمها','تركها وحدها'],['تثبيت الأم أولًا ثم التخطيط للولادة بحسب الحالة السريرية','تأخير كل التدبير لأسابيع','إخراجها بعد الاختلاج','علاج الصداع فقط']],pph:[['استدعاء المساعدة وتقييم ABC وقياس النزف وبدء الإنعاش','الانتظار ٣٠ دقيقة','إخراج المريضة','إعطاء مسكن فقط'],['وهن الرحم','حمل هاجر','مشيمة منزاحة قبل الولادة','فرط الإقياء'],['تدليك الرحم وإعطاء قابضات الرحم وفق البروتوكول مع استمرار الإنعاش','انتظار الإيكو قبل التدخل','تجاهل النزف','إعطاء ميثوتركسات'],['إعطاء حمض الترانيكساميك وريديًا مبكرًا خلال ٣ ساعات من الولادة وفق البروتوكول','إعطاء ميثوتركسات','تأخير العلاج','إيقاف الإنعاش'],['تفعيل استجابة النزف والتصعيد للسيطرة النهائية على النزف ومنتجات الدم حسب الحاجة','إرسال المريضة للمنزل','إيقاف المراقبة','الانتظار عدة ساعات']],shoulder:[['عسر ولادة الكتف','ولادة طبيعية','انفصال مشيمة','إرجاج'],['استدعاء المساعدة وإعلان الطوارئ وتجنب الشد المفرط','الشد بقوة أكبر على الرأس','ترك المريضة','الانتظار'],['مناورة ماكروبرتس مع الضغط فوق العانة عند اللزوم','الضغط على قاع الرحم','الشد القوي للأسفل','شق العجان وحده'],['تقييم الوليد والأم للمضاعفات وتوثيق الحالة الإسعافية','إيقاف المراقبة فورًا','تجاهل نزف الأم','افتراض عدم وجود أذية']]};return maps[id]?.[st]?.[i]||s[3][i]}
function updateHealth(){health=Math.max(0,Math.min(100,health));$('health').textContent=health;$('healthBar').style.width=health+'%';$('stability').textContent=health<50?(lang==='ar'?'حرجة':'Critical'):health<80?(lang==='ar'?'تحتاج مراقبة':'Watch'):(lang==='ar'?'مستقرة':'Stable')}
function renderTimeline(){$('timeline').innerHTML=CASES[levelId].steps.map((s,i)=>`<div class="timeItem ${i<step?'done':''} ${i===step?'active':''}"><span>${i<step?'✓':i+1}</span><b>${s[0]}</b></div>`).join('')}
function startLevel(id){levelId=id;step=0;score=0;health=100;errors=0;correct=0;answered=false;$('home').classList.add('hidden');$('levels').classList.add('hidden');$('end').classList.add('hidden');$('game').classList.remove('hidden');$('score').textContent=0;renderStep();window.scrollTo({top:0,behavior:'smooth'})}
function answer(i){if(answered)return;answered=true;const s=CASES[levelId].steps[step],ok=i===s[4];const fb=$('feedback');document.querySelectorAll('.choice').forEach((b,n)=>{b.disabled=true;if(n===s[4])b.classList.add('correct');if(n===i&&!ok)b.classList.add('wrong')});if(ok){correct++;score+=100;health=Math.min(100,health+3);fb.innerHTML=`<b>✅ ${lang==='ar'?'قرار صحيح':'Correct decision'}</b><p>${lang==='ar'?s[6]:s[5]}</p>`}else{errors++;score=Math.max(0,score-50);health=Math.max(0,health-18);fb.innerHTML=`<b>⚠️ ${lang==='ar'?'مراجعة القرار':'Review the decision'}</b><p>${lang==='ar'?s[6]:s[5]}</p>`}$('score').textContent=score;updateHealth();fb.className='feedback';$('nextBtn').textContent=step===CASES[levelId].steps.length-1?T[lang].complete:T[lang].continue;$('nextBtn').classList.remove('hidden')}
function next(){if(!answered)return;if(step<CASES[levelId].steps.length-1){step++;renderStep()}else finish()}
function finish(){const total=CASES[levelId].steps.length;const pct=Math.round(correct/total*100);const max=unlocked();if(correct>=Math.ceil(total*.75)){localStorage.setItem('obgynUnlocked',String(Math.min(ids.length,Math.max(max,ids.indexOf(levelId)+2))))}$('game').classList.add('hidden');$('end').classList.remove('hidden');$('finalScore').textContent=score;$('correctCount').textContent=`${correct}/${total}`;$('errorCount').textContent=errors;$('finalHealth').textContent=`${health}%`;$('rank').textContent=pct>=90?'💎 Emergency Expert':pct>=75?'🥇 Senior Resident':pct>=60?'🥈 Junior Resident':'🥉 Keep Practicing';$('endMessage').textContent=pct>=90?T[lang].excellent:pct>=60?T[lang].good:T[lang].needs;$('clinicalRefs').innerHTML=`<div class="credits"><div class="eyebrow">${lang==='ar'?'مراجع سريرية':'CLINICAL REFERENCES'}</div><p>${lang==='ar'?'تمت مراجعة المبادئ التعليمية وفق إرشادات ACOG وWHO وRCOG وNICE. يجب الرجوع إلى البروتوكول المحلي.':'Educational principles reviewed against ACOG, WHO, RCOG and NICE guidance. Always follow local protocols.'}</p></div>`;window.scrollTo({top:0,behavior:'smooth'})}
function setLanguage(){lang=lang==='en'?'ar':'en';localStorage.setItem('obgynLang',lang);applyText()}
$('startBtn').onclick=()=>{$('home').classList.add('hidden');$('levels').classList.remove('hidden');renderLevels()};$('backHome').onclick=()=>{$('levels').classList.add('hidden');$('home').classList.remove('hidden')};$('quitBtn').onclick=()=>{$('game').classList.add('hidden');$('levels').classList.remove('hidden');renderLevels()};$('nextBtn').onclick=next;$('replayBtn').onclick=()=>startLevel(levelId);$('levelsBtn').onclick=()=>{$('end').classList.add('hidden');$('levels').classList.remove('hidden');renderLevels()};$('langBtn').onclick=setLanguage;$('musicBtn').style.display='none';applyText();