/* OB/GYN Emergency Challenge — enhancement layer
   Educational simulation. Clinical content reviewed against ACOG, RCOG and NICE guidance.
*/
(function(){
  const AR={
    ectopic:{patient:'٢٨ سنة • حمل ٧ أسابيع',q:['ما الإجراء الأول؟','ماذا تعني العلامات الحيوية؟','ما التشخيص الأكثر احتمالًا؟','ما التوجه النهائي؟'],c:[['ابدأ بتقييم ABC والإنعاش واستدعاء المساعدة','انتظر نتيجة β-hCG','أعطِ ميثوتركسات فورًا','أخرج المريضة'],['عدم الاستقرار الديناميكي الدموي','حمل مبكر طبيعي','مستقرة لأن SpO₂ طبيعي','لا حاجة لأي إجراء'],['حمل هاجر متمزق','مشيمة منزاحة','فرط إقياء','حمل طبيعي'],['تدبير جراحي إسعافي مع استمرار الإنعاش','انتظر β-hCG متسلسلًا','ميثوتركسات ومراقبة','متابعة خارجية']]},
    normalbirth:{patient:'٢٥ سنة • ٣٩+٢ أسبوع • مخاض فعال',q:['ما الخطوة المناسبة؟','ما الأولوية؟','ماذا تفعل بعد الولادة؟','ما أفضل متابعة؟'],c:[['دعم المخاض والاستمرار بتقييم الأم والجنين','عملية قيصرية فورية','إيقاف كل المراقبة','إعطاء مغنزيوم سلفات'],['دعم الولادة المضبوطة ومراقبة الأم والجنين','ضغط روتيني على قاع الرحم','الشد بقوة على الرأس','مغادرة الغرفة'],['تقييم الوليد ودعم التلامس جلدًا لجلد ومراقبة الأم','تجاهل توتر الرحم','فصل الأم والوليد دون داعٍ','إعطاء أوكسيتوسين فقط عند حدوث نزف شديد'],['استمرار المراقبة بعد الولادة وتقييم النزف وتوتر الرحم','إخراج المريضة فورًا','إيقاف كل المراقبة','طلب CT']]},
    preeclampsia:{patient:'٣١ سنة • ٣٥ أسبوعًا • ضغط 170/112 وأعراض بصرية',q:['ما الأولوية الآن؟','ما الدواء المستخدم للوقاية من الاختلاجات؟','ماذا تفعل أثناء الاختلاج؟','ما المبدأ الصحيح بعد التثبيت؟'],c:[['التعرف على ارتفاع الضغط الشديد وبدء خفض الضغط العاجل مع تقييم الأم والجنين','إرسالها للمنزل','الانتظار حتى الغد','إعطاء السوائل الفموية فقط'],['مغنزيوم سلفات','ميثوتركسات','أوكسيتوسين','وارفارين'],['تأمين السلامة والطريق الهوائي، استدعاء المساعدة وإعطاء مغنزيوم سلفات وفق البروتوكول','تقييدها بقوة','وضع شيء في فمها','تركها وحدها'],['تثبيت الأم أولًا ثم التخطيط للولادة بحسب الحالة السريرية وعمر الحمل','تأخير كل التدبير لأسابيع','إخراجها بعد الاختلاج','علاج الصداع فقط']]},
    pph:{patient:'٢٩ سنة • بعد ٢٠ دقيقة من الولادة المهبلية',q:['ما الأولوية؟','ما السبب الأكثر احتمالًا؟','ما التدبير الأولي المناسب؟','ما الإضافة المهمة إذا كان النزف مشخصًا؟'],c:[['استدعاء المساعدة وتقييم ABC وبدء الإنعاش وتحديد سبب النزف','الانتظار ٣٠ دقيقة','إخراج المريضة','إعطاء مسكن فقط'],['وهن الرحم','حمل هاجر','مشيمة منزاحة قبل الولادة','فرط الإقياء'],['تدليك الرحم وإعطاء قابضات الرحم وفق البروتوكول مع استمرار الإنعاش','انتظار الإيكو قبل التدخل','تجاهل النزف','إعطاء ميثوتركسات'],['إعطاء حمض الترانيكساميك وريديًا مبكرًا عند تشخيص نزف ما بعد الولادة، ويفضل خلال ٣ ساعات من الولادة، وفق البروتوكول','إعطاء ميثوتركسات','تأخير العلاج حتى الغد','إيقاف الإنعاش']]},
    shoulder:{patient:'٣٠ سنة • حمل تام • وُلد الرأس ولم تلد الكتفين',q:['ما التشخيص؟','ما أول خطوة تنظيمية؟','ما المناورة المناسبة؟','ماذا بعد ولادة الطفل؟'],c:[['عسر ولادة الكتف','ولادة طبيعية','انفصال مشيمة','إرجاج'],['استدعاء المساعدة وإعلان الطوارئ وإيقاف الشد على الرأس','الشد بقوة أكبر على الرأس','ترك المريضة','الانتظار'],['مناورة ماكروبرتس مع الضغط فوق العانة عند اللزوم','الضغط على قاع الرحم','الشد القوي للأسفل','شق العجان وحده'],['تقييم الوليد والأم للمضاعفات وتوثيق الحالة الإسعافية','إيقاف المراقبة فورًا','تجاهل نزف الأم','افتراض عدم وجود أذية']]}
  };

  CASES.preeclampsia.steps[0]=['Red flag','BP 170/112 with severe headache and visual symptoms at 35 weeks.','What is the priority?',['Recognize severe hypertension and urgently start appropriate antihypertensive treatment while assessing mother and fetus','Send home to rest','Wait until tomorrow','Give only oral fluids'],0,'Acute-onset severe hypertension requires urgent treatment; assess and stabilize the mother while evaluating the fetus.','ارتفاع الضغط الشديد الحاد يتطلب علاجًا عاجلًا؛ ثبّت الأم وقيّم الجنين بالتوازي.'];
  CASES.pph.steps[2]=['First-line action','Atony is suspected and bleeding continues.','What is the appropriate action?',['Uterine massage plus uterotonic treatment according to protocol while resuscitation continues','Wait for ultrasound before acting','Ignore the bleeding','Give methotrexate'],0,'Uterine massage, uterotonics and resuscitation are core early measures for atony.','تدليك الرحم وقابضات الرحم والإنعاش من الإجراءات المبكرة الأساسية عند وهن الرحم.'];
  CASES.pph.steps[3]=['TXA','PPH is diagnosed and bleeding is ongoing.','What important adjunct should be considered?',['Early IV tranexamic acid, ideally within 3 hours of birth, in addition to standard care','Methotrexate','Delay treatment until tomorrow','Stop resuscitation'],0,'Early IV tranexamic acid is recommended for clinically diagnosed PPH as soon as possible and within 3 hours of birth, alongside standard care.','يوصى بحمض الترانيكساميك وريديًا مبكرًا عند تشخيص نزف ما بعد الولادة، بأسرع وقت وخلال ٣ ساعات من الولادة، إضافةً إلى التدبير القياسي.'];

  CASES.abruption={emoji:'🩸',patient:'Rana',details:'34 years • 36 weeks • painful bleeding',en:'Placental Abruption',ar:'انفصال المشيمة المبكر',steps:[
    ['Recognition','A 36-week patient has sudden painful vaginal bleeding, uterine tenderness and a firm, tense uterus.','What is the most likely diagnosis?',['Placental abruption','Placenta previa','Ectopic pregnancy','Normal labor'],0,'Painful bleeding with uterine tenderness is concerning for placental abruption.','النزف المؤلم مع إيلام الرحم يثير الشك بانفصال المشيمة المبكر.'],
    ['Stabilize','She is tachycardic and looks unwell.','What is the priority?',['Assess ABCs, establish IV access, resuscitate and assess maternal/fetal status','Wait for imaging before resuscitation','Discharge her','Give methotrexate'],0,'Maternal stabilization and assessment of fetal status are immediate priorities.','الأولوية هي تثبيت الأم وتقييم حالتها وحالة الجنين بشكل عاجل.'],
    ['Fetal status','The fetal heart rate becomes persistently abnormal and the mother remains unstable.','What principle guides management?',['Expedite delivery when indicated by maternal or fetal compromise after appropriate stabilization','Delay delivery for several days regardless of status','Give tocolysis and discharge','Ignore the fetal heart rate'],0,'Maternal or fetal compromise may require expedited delivery after stabilization and team escalation.','تدهور حالة الأم أو الجنين قد يستدعي تسريع الولادة بعد التثبيت والتصعيد للفريق المختص.'],
    ['Bleeding','The team prepares blood products and continues close monitoring.','What is important?',['Anticipate hemorrhage and coagulopathy and manage with a multidisciplinary hemorrhage response','Assume blood loss is minimal','Stop monitoring','Use methotrexate'],0,'Abruption can cause major hemorrhage and coagulopathy; prepare blood products and monitor closely.','قد يسبب الانفصال نزفًا شديدًا واضطراب تخثر؛ حضّر مشتقات الدم وراقب المريضة عن قرب.']
  ]};
  CASES.collapse={emoji:'🚑',patient:'Maya',details:'30 years • postpartum • sudden collapse',en:'Maternal Collapse',ar:'انهيار الأم الحاد',steps:[
    ['Alarm','A postpartum patient suddenly collapses and is unresponsive.','What is the first response?',['Call for help and start an immediate ABC assessment; begin resuscitation as indicated','Wait for laboratory results','Move her to a quiet room','Give oral fluids'],0,'Maternal collapse is an emergency: call for help and begin immediate resuscitation.','انهيار الأم حالة إسعافية: استدعِ المساعدة وابدأ تقييم ABC والإنعاش فورًا.'],
    ['CPR','She has no normal breathing and no signs of circulation.','What should happen next?',['Start high-quality CPR and follow the maternal cardiac arrest protocol','Wait for an ECG before compressions','Give methotrexate','Leave the patient alone'],0,'If cardiac arrest is suspected, start CPR immediately and follow the maternal arrest algorithm.','عند الاشتباه بتوقف القلب ابدأ الإنعاش القلبي الرئوي فورًا واتبع خوارزمية توقف القلب عند الحامل/النفاسية.'],
    ['Cause','The team searches for reversible causes while resuscitation continues.','What is the best approach?',['Consider reversible causes such as hemorrhage, thromboembolism, eclampsia and sepsis while continuing resuscitation','Stop CPR to investigate','Assume anxiety','Treat only pain'],0,'Search for and treat reversible causes without interrupting effective resuscitation.','ابحث عن الأسباب القابلة للعكس وعالجها دون إيقاف الإنعاش الفعال.'],
    ['Debrief','After return of circulation, the team stabilizes the patient.','What is important afterward?',['Continue critical monitoring, identify the cause and document/debrief the emergency','Discharge immediately','Stop monitoring','Ignore the event'],0,'Post-arrest care includes ongoing monitoring, cause identification, documentation and team debriefing.','بعد عودة الدوران تستمر المراقبة الحرجة وتحديد السبب والتوثيق ومراجعة الحدث مع الفريق.']
  ]};

  const ENQ={Arrival:'What is the first action?',Clues:'What do the vital signs indicate?',Ultrasound:'What is the most likely diagnosis?','Act now':'What is the definitive approach?','Second stage':'What is the priority?','After birth':'What should you do after birth?','Third stage':'What is the best follow-up?','Red flag':'What is the priority?','Prevent seizure':'Which medication is used for seizure prophylaxis?',Seizure:'What should you do first?','Definitive plan':'What is the correct principle?',Alarm:'What is the priority?',Tone:'What is the most likely cause?','First-line action':'What is the appropriate action?',Escalate:'What should you do?',Recognition:'What is the diagnosis?',Call:'What is the first organizational step?',Maneuver:'Which maneuver is appropriate?',TXA:'What important adjunct should be considered?',Stabilize:'What is the priority?','Fetal status':'What principle guides management?',Bleeding:'What is important?',CPR:'What should happen next?',Cause:'What is the best approach?',Debrief:'What is important afterward?'};

  function getAr(id,st){return AR[id]||null}
  function render(){
    const max=Math.min(7,Math.max(1,Number(localStorage.getItem('obgynUnlocked')||1)));
    $('levelGrid').innerHTML=Object.entries(CASES).map(([id,c],i)=>{const locked=i+1>max;return `<button class="levelCard ${locked?'locked':''}" data-id="${id}" ${locked?'disabled':''}><div class="levelNo">${lang==='ar'?'المستوى':'LEVEL'} ${i+1}</div><div class="levelEmoji">${c.emoji}</div><h3>${lang==='ar'?c.ar:c.en}</h3><p>${lang==='ar'?(AR[id]?.patient||c.details):c.details}</p><span>${locked?'🔒 '+(lang==='ar'?'أكمل المستوى السابق':'Complete the previous level'):'▶ '+(lang==='ar'?'ابدأ الحالة':'Start case')}</span></button>`}).join('');
    document.querySelectorAll('.levelCard:not(.locked)').forEach(b=>b.onclick=()=>startLevel(b.dataset.id));
  }
  window.renderLevels=render;

  window.renderStep=function(){
    const c=CASES[levelId],s=c.steps[step],ar=getAr(levelId,step);
    $('caseTag').textContent=`${lang==='ar'?'المستوى':'LEVEL'} ${Object.keys(CASES).indexOf(levelId)+1}`;$('caseTitle').textContent=lang==='ar'?c.ar:c.en;$('progress').textContent=`${step+1} / ${c.steps.length}`;
    $('caseBrief').textContent=s[1];$('visualLabel').textContent=lang==='ar'?'المشهد السريري':'CLINICAL SCENE';$('visualArt').innerHTML=scene(c.emoji,levelId,step);$('patientName').textContent=c.patient;$('patientDetails').textContent=lang==='ar'?(ar?.patient||c.ar):c.details;
    $('health').textContent=health;$('healthBar').style.width=health+'%';$('stability').textContent=health<60?(lang==='ar'?'حرجة':'Critical'):(health<85?(lang==='ar'?'تحتاج مراقبة':'Watch'):(lang==='ar'?'مستقرة':'Stable'));
    const q=lang==='ar'?(ar?.q[step]||s[2]):(ENQ[s[0]]||s[2]);const choices=lang==='ar'?(ar?.c[step]||s[3]):s[3];
    $('choices').innerHTML=`<h3 class="question">${q}</h3>`+choices.map((x,i)=>`<button class="choice" data-i="${i}"><span class="letter">${String.fromCharCode(65+i)}</span><span>${x}</span></button>`).join('');$('feedback').className='feedback hidden';$('nextBtn').classList.add('hidden');answered=false;
    document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>answer(Number(b.dataset.i)));renderTimeline();
  };

  window.finishLevel=function(){const idx=Object.keys(CASES).indexOf(levelId)+1;localStorage.setItem('obgynUnlocked',String(Math.max(maxUnlock(),Math.min(7,idx+1))));$('finalScore').textContent=score;$('correctCount').textContent=`${correct}/${CASES[levelId].steps.length}`;$('errorCount').textContent=errors;$('finalHealth').textContent=health+'%';$('rank').textContent=correct===CASES[levelId].steps.length?(lang==='ar'?'خبير طوارئ':'Emergency Master'):(correct>=Math.ceil(CASES[levelId].steps.length*.75)?(lang==='ar'?'مستجيب ممتاز':'Emergency Responder'):(lang==='ar'?'بحاجة إلى تدريب':'Needs More Practice'));$('endMessage').textContent=correct===CASES[levelId].steps.length?(lang==='ar'?'🔥 ممتاز! ترتيب أولويات سريري رائع.':'🔥 Excellent clinical prioritization!'):(lang==='ar'?'راجع القرارات الخاطئة وحاول مجددًا.':'Review the missed decisions and try again.');addReferences();show('end')};
  function maxUnlock(){return Math.min(7,Math.max(1,Number(localStorage.getItem('obgynUnlocked')||1)))}

  function addReferences(){let box=$('clinicalRefs');if(!box){box=document.createElement('div');box.id='clinicalRefs';box.className='clinicalRefs';$('end').appendChild(box)}box.innerHTML=`<h3>${lang==='ar'?'📚 المراجع العلمية':'📚 Clinical references'}</h3><p>${lang==='ar'?'تمت مراجعة نقاط التعلم الأساسية وفق الإرشادات المهنية. يجب تطبيق البروتوكول المحلي في الممارسة الواقعية.':'Core learning points were checked against professional guidance. Local protocols must be followed in real clinical care.'}</p><ul><li><a href="https://www.acog.org/clinical/clinical-guidance/practice-bulletin/articles/2020/06/gestational-hypertension-and-preeclampsia" target="_blank">ACOG — Gestational Hypertension and Preeclampsia</a></li><li><a href="https://www.acog.org/clinical/clinical-guidance/practice-bulletin/articles/2017/10/postpartum-hemorrhage" target="_blank">ACOG — Postpartum Hemorrhage</a></li><li><a href="https://www.rcog.org.uk/guidance/browse-all-guidance/green-top-guidelines/shoulder-dystocia-green-top-guideline-no-42/" target="_blank">RCOG — Shoulder Dystocia</a></li><li><a href="https://www.nice.org.uk/guidance/ng126" target="_blank">NICE — Ectopic Pregnancy and Miscarriage</a></li></ul>`}

  /* Reliable background music: Web Audio melody starts only after user interaction, avoiding autoplay blocking. */
  let musicCtx=null,musicGain=null,musicTimer=null,musicOn=false,beat=0;const notes=[220,247,262,294,330,294,262,247];
  function musicStart(){if(musicOn)return;try{musicCtx=musicCtx||new(window.AudioContext||window.webkitAudioContext)();if(musicCtx.state==='suspended')musicCtx.resume();musicGain=musicGain||musicCtx.createGain();musicGain.gain.value=.035;musicGain.connect(musicCtx.destination);musicOn=true;beat=0;const tick=()=>{if(!musicOn)return;const o=musicCtx.createOscillator(),g=musicCtx.createGain();o.type='sine';o.frequency.value=notes[beat++%notes.length];g.gain.setValueAtTime(.0001,musicCtx.currentTime);g.gain.exponentialRampToValueAtTime(.055,musicCtx.currentTime+.03);g.gain.exponentialRampToValueAtTime(.0001,musicCtx.currentTime+.42);o.connect(g);g.connect(musicGain);o.start();o.stop(musicCtx.currentTime+.45);musicTimer=setTimeout(tick,520)};tick();$('musicBtn').textContent=lang==='ar'?'🔊 الموسيقى تعمل':'🔊 Music ON'}catch(e){$('musicBtn').textContent=lang==='ar'?'⚠️ شغّل الصوت':'⚠️ Click to enable'}}
  function musicStop(){musicOn=false;if(musicTimer)clearTimeout(musicTimer);if(musicGain)musicGain.gain.value=.0001;$('musicBtn').textContent=lang==='ar'?'🔇 الموسيقى متوقفة':'🔇 Music OFF'}
  $('musicBtn').onclick=()=>musicOn?musicStop():musicStart();
  window.startMusic=musicStart;

  const oldSetLang=window.setLang;window.setLang=function(){oldSetLang();render();$('disclaimer').textContent=lang==='ar'?'محاكاة تعليمية فقط، وليست بديلًا عن البروتوكول المحلي أو الإشراف السريري.':'Educational simulation only; not a substitute for local protocols or clinical supervision.';if(levelId!==null&&!$('game').classList.contains('hidden'))renderStep();if($('end')&&!$('end').classList.contains('hidden'))addReferences();};
  $('langBtn').onclick=()=>{lang=lang==='en'?'ar':'en';$('langBtn').textContent=lang==='ar'?'English 🇬🇧':'عربي 🇸🇾';setLang()};
  setTimeout(()=>render(),0);
})();